import { Product } from '../../types';

export const menList: Product[] = [

  // --- السعودية الاحترافية (AR Men - SEO & AI Optimized) ---
  {
    id: 'ksa-1',
    name: 'تيار القمة - Neon Calligraphy Tee',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/1sa.webp',
    region: 'ar',
    gender: 'men',
    category: 'Jersey',
    description: "جسد طاقة اللعب اللامتناهية مع 'تيار القمة'. تصميم يدمج فن الخط العربي مع إضاءة النيون العصرية.",
    metaTitle: "تيشيرت تيار القمة نيون | ستريت وير خط عربي | Folklore FC",
    metaDescription: "اكتشف تيشيرت تيار القمة بتصميم الخط العربي والنيون. مزيج بين الأصالة والحداثة لمحبي الستريت وير في السعودية. اطلبه الآن.",
    altText: "تيشيرت أسود رجالي بكلمات عربية مضيئة بالنيون الأخضر بأسلوب ستريت وير عصري.",
    keywords: ["تيشيرت نيون سعودي", "خط عربي مودرن", "ملابس رجالية الرياض", "فولكلور إف سي"]
  },
  {
    id: 'ksa-2',
    name: 'طريق النصر - Desert Vintage Edition',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/2sa.webp',
    region: 'ar',
    gender: 'men',
    category: 'Jersey',
    description: "استرجع عبق الماضي مع 'طريق النصر'. تصميم كلاسيكي يصور رحلة اللاعب في قلب الصحراء الشاسعة.",
    metaTitle: "تيشيرت طريق النصر كلاسيك | تراث الصحراء السعودية | Folklore FC",
    metaDescription: "عش هيبة الماضي مع تيشيرت طريق النصر. تصميم فينتج يروي قصة التحدي في قلب الصحراء. جودة قطنية فخمة وتوصيل سريع.",
    altText: "تصميم فينتج على تيشيرت يظهر لاعباً في الصحراء مع جملة طريق النصر بألوان تراثية.",
    keywords: ["تيشيرت فينتج سعودي", "تراث الصحراء", "ملابس اليوم الوطني", "أزياء رجالية تراثية"]
  },
  {
    id: 'ksa-3',
    name: 'عزم الرجال - Tactical Resolve Tee',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/3sa.webp',
    region: 'ar',
    gender: 'men',
    category: 'Jersey',
    description: "تصميم 'عزم الرجال' يعكس القوة والعزيمة داخل الملعب بمظهر تكتيكي مستوحى من الشموخ السعودي.",
    metaTitle: "تيشيرت عزم الرجال التكتيكي | قوة الشموخ السعودي | Folklore FC",
    metaDescription: "عبر عن قوتك بتصميم عزم الرجال. تيشيرت تكتيكي يجمع بين الهوية الوطنية وروح المحارب. مثالي للنادي والإطلالات الجريئة.",
    altText: "تيشيرت رجالي بتصميم عسكري تكتيكي يدمج شعارات سعودية ورموز كروية قوية.",
    keywords: ["تيشيرت تكتيكي رجالي", "عزم الرجال", "ملابس رياضية قوية", "KSA Tactical Wear"]
  },
  {
    id: 'ksa-4',
    name: 'جوهر القوة - Cyborg Heart Football',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/4sa.webp',
    region: 'ar',
    gender: 'men',
    category: 'Jersey',
    description: "عندما تنبض كرة القدم في العروق. تصميم مستقبلي يظهر 'جوهر القوة' كقلب تكنولوجي ينبض بشغف اللعبة.",
    metaTitle: "تيشيرت جوهر القوة سايبر | قلب كروي مستقبلي | Folklore FC",
    metaDescription: "تيشيرت جوهر القوة لمحبي التصاميم المستقبلية. قلب ميكانيكي مدمج بالهوية السعودية الأصيلة. قطعة حصرية من فولكلور إف سي.",
    altText: "تصميم قلب آلي (سايبورغ) ينبض باللون الأخضر وسط تيشيرت أسود فخم.",
    keywords: ["تيشيرت سايبربانك", "جوهر القوة", "ملابس رجالية مستقبلية", "تصميم مبتكر"]
  },
  {
    id: 'ksa-5',
    name: 'الصقور الخضر - Kingdom Heritage Tee',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/5sa.webp',
    region: 'ar',
    gender: 'men',
    category: 'Jersey',
    description: "احتفاءٌ بأرض الحرمين ومعالم المملكة الشامخة. يجمع بين الصقر كرمز للقوة والمعالم العمرانية الحديثة.",
    metaTitle: "تيشيرت الصقور الخضر | تراث ومعالم المملكة | Folklore FC",
    metaDescription: "ارتدِ فخر الانتماء مع تيشيرت الصقور الخضر. يدمج بين قوة الصقر ومعالم الرياض وجدة الحديثة. تصميم يعبر عن رؤية المملكة.",
    altText: "رسم فني يجمع صقراً محلقاً فوق أبراج الرياض وناطحات السحاب على تيشيرت أبيض.",
    keywords: ["الصقور الخضر", "تيشيرت معالم السعودية", "فخر المملكة", "ملابس وطنية رجالية"]
  },
  {
    id: 'ksa-6',
    name: 'صانع اللعب - Artist Calligraphy Tee',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/6sa.webp',
    region: 'ar',
    gender: 'men',
    category: 'Jersey',
    description: "فن 'صناعة اللعب' يتجسد في الكلمات العربية التي تشكل جسد اللاعب وحركته الانسيابية.",
    metaTitle: "تيشيرت صانع اللعب | فن الخط العربي الكروي | Folklore FC",
    metaDescription: "لأصحاب المهارة العالية. تيشيرت صانع اللعب يدمج بين انسيابية الخط العربي وجماليات كرة القدم. قطعة فنية راقية.",
    altText: "تيشيرت يظهر لاعباً مرسوماً بالكامل من كلمات الخط العربي أثناء ركل الكرة.",
    keywords: ["تيشيرت خط عربي", "صانع اللعب", "ملابس فنية رجالية", "أزياء سعودية فاخرة"]
  },
  {
    id: 'ksa-7',
    name: 'المهارة الذهبية - Green & Gold Script',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/7sa.webp',
    region: 'ar',
    gender: 'men',
    category: 'Jersey',
    description: "مزيج فاخر من الأخضر والذهبي يبرز جمالية الخط العربي بأسلوب الـ Splatter الفني المعاصر.",
    metaTitle: "تيشيرت المهارة الذهبية | فخامة الأخضر والذهب | Folklore FC",
    metaDescription: "تيشيرت المهارة الذهبية يجمع بين التميز والأسلوب الفني المعاصر. تصميم ذهبي فخم يعبر عن الموهبة السعودية الفطرية.",
    altText: "تيشيرت أسود عليه بقع ألوان ذهبية وخضراء مع كلمات عربية منقوشة بدقة.",
    keywords: ["تيشيرت ذهبي رجالي", "المهارة الذهبية", "ستريت وير فخم", "ملابس هيب هوب سعودي"]
  },
  {
    id: 'ksa-8',
    name: 'سد منيع - Fortress Defense Tee',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/8sa.webp',
    region: 'ar',
    gender: 'men',
    category: 'Jersey',
    description: "مستوحى من القلاع والحصون التاريخية، يجسد قوة الدفاع وحماية العرين بدمج العمارة التراثية بالمرمى.",
    metaTitle: "تيشيرت سد منيع | حصون الدفاع السعودية | Folklore FC",
    metaDescription: "جسد الثبات والإصرار مع تيشيرت سد منيع. تصميم يربط عراقة الحصون التاريخية بقوة المدافع في الملعب. تسوق الآن.",
    altText: "تصميم يظهر قلعة سعودية قديمة تتحول إلى مرمى كرة قدم منيع على تيشيرت أبيض.",
    keywords: ["تيشيرت تراثي", "سد منيع", "حصون السعودية", "ملابس دفاع كرة قدم"]
  },
  {
    id: 'ksa-9',
    name: 'جسارة - Street Boldness Edition',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/9sa.webp',
    region: 'ar',
    gender: 'men',
    category: 'Jersey',
    description: "يدمج بين ثقافة الحذاء الرياضي (Sneaker Culture) وكرة القدم بأسلوب الـ Graffiti لروح التحدي.",
    metaTitle: "تيشيرت جسارة غرافيتي | ثقافة الشارع السعودية | Folklore FC",
    metaDescription: "للجريئين فقط. تيشيرت جسارة يجمع بين فن الغرافيتي وثقافة الأحذية الرياضية في ملاعب الشارع السعودية. تصميم مليء بالطاقة.",
    altText: "رسم غرافيتي ملون لحذاء رياضي يطأ كرة قدم مع كلمة جسارة بخط عريض.",
    keywords: ["تيشيرت غرافيتي", "جسارة", "Streetwear KSA", "ملابس شبابية الرياض"]
  },
  {
    id: 'ksa-10',
    name: 'تردد النصر - Victory Frequency',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/10sa.webp',
    region: 'ar',
    gender: 'men',
    category: 'Jersey',
    description: "تصميم مستقبلي باللون الأخضر النيون يصور اللاعب كموجة طاقة لا تتوقف تعزف ألحان الفوز.",
    metaTitle: "تيشيرت تردد النصر | طاقة الفوز الخضراء | Folklore FC",
    metaDescription: "استشعر إيقاع المدرجات مع تيشيرت تردد النصر. تصميم مستقبلي يجسد موجات الطاقة والانتصار بلمسة نيون خضراء.",
    altText: "تيشيرت أسود يظهر ذبذبات طاقة خضراء على شكل لاعب كرة قدم مندفع.",
    keywords: ["تيشيرت نيون", "تردد النصر", "ملابس جيم رجالية", "أزياء رياضية حديثة"]
  },
  {
    id: 'ksa-11',
    name: 'ليث الميدان - Lion of the Pitch',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/11sa.webp',
    region: 'ar',
    gender: 'men',
    category: 'Jersey',
    description: "يجمع بين شراسة الأسد ومهارة اللاعب السعودي، مع لمسات فنية صاخبة تعبر عن القوة والهيمنة.",
    metaTitle: "تيشيرت ليث الميدان | قوة الأسد السعودي | Folklore FC",
    metaDescription: "زئير الملاعب في قميص واحد. تيشيرت ليث الميدان يعبر عن الهيمنة والشراسة الرياضية بتصميم فني مذهل. اطلبه اليوم.",
    altText: "رسم قوي لرأس أسد يندمج مع ملامح لاعب كرة قدم غاضب ومصمم على الفوز.",
    keywords: ["تيشيرت أسد", "ليث الميدان", "ملابس رجالية قوية", "تصميم وحوش رياضي"]
  },
  {
    id: 'ksa-12',
    name: 'فرسان الصحراء - Warrior Legends',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/12sa.webp',
    region: 'ar',
    gender: 'men',
    category: 'Jersey',
    description: "ركلة مقصية أسطورية يمتزج فيها السيف والدرع بكرة القدم أمام حصون المملكة التاريخية.",
    metaTitle: "تيشيرت فرسان الصحراء | ملاحم البطولة السعودية | Folklore FC",
    metaDescription: "أعد إحياء الأساطير مع تيشيرت فرسان الصحراء. تصميم يجمع بين الفروسية العربية ومهارة الكرة بأسلوب ملحمي فريد.",
    altText: "لاعب يقوم بركلة مقصية وبجانبه سيف ودرع عربي قديم مع قلعة في الخلفية.",
    keywords: ["فرسان الصحراء", "تيشيرت ملحمي", "ملابس تراثية مطورة", "أساطير الكرة"]
  },
  {
    id: 'ksa-13',
    name: 'فخر الانتماء - Calligraphic Pride',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/13sa.webp',
    region: 'ar',
    gender: 'men',
    category: 'Jersey',
    description: "يستخدم الخط العربي الانسيابي لرسم حركة اللاعب، مما يخلق قطعة فنية راقية تحتفي بالهوية.",
    metaTitle: "تيشيرت فخر الانتماء | رقي الخط العربي | Folklore FC",
    metaDescription: "بساطة التصميم وعمق المعنى. تيشيرت فخر الانتماء يجسد الهوية السعودية عبر جماليات الخط العربي. فخامة وأصالة.",
    altText: "تيشيرت أبيض بلمسات خط عربي ذهبي تشكل قوام لاعب رياضي متميز.",
    keywords: ["تيشيرت فخر الانتماء", "خط عربي فاخر", "ملابس هدايا سعودية", "ستريت وير راقي"]
  },
  {
    id: 'ksa-14',
    name: 'روح الصحراء - Desert Spirit Kit',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/14sa.webp',
    region: 'ar',
    gender: 'men',
    category: 'Jersey',
    description: "من قلب الكثبان الرملية إلى منصات التتويج. تصميم كلاسيكي يجمع بين الطبيعة وفن الكرة.",
    metaTitle: "تيشيرت روح الصحراء | هدوء وأصالة الرمال | Folklore FC",
    metaDescription: "تيشيرت روح الصحراء يجسد الطبيعة الخلابة للمملكة في قالب رياضي كلاسيكي. مثالي لمن يقدر الهدوء والتميز التراثي.",
    altText: "تيشيرت بألوان ترابية ورملية يظهر كثباناً تتحول تدريجياً إلى ملعب كرة قدم.",
    keywords: ["روح الصحراء", "تيشيرت رملي", "ملابس رياضية كلاسيك", "ألوان ترابية"]
  },
  {
    id: 'ksa-15',
    name: 'سيد الساحة - Master of the Pitch',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/15sa.webp',
    region: 'ar',
    gender: 'men',
    category: 'Jersey',
    description: "خلفية من الزخارف الهندسية الإسلامية الفاخرة تبرز هيبة اللاعب وتفانيه في الملعب.",
    metaTitle: "تيشيرت سيد الساحة | زخارف إسلامية ملكية | Folklore FC",
    metaDescription: "تيشيرت سيد الساحة لمن يبحث عن الفخامة. تصميم يدمج الزخارف الهندسية الإسلامية مع هيبة نجوم الكرة. تميز في كل مباراة.",
    altText: "تيشيرت أسود بذهب وزخارف هندسية معقدة تحيط برسم لاعب مسيطر على الكرة.",
    keywords: ["سيد الساحة", "زخارف إسلامية", "تيشيرت ملكي رجالي", "ملابس مناسبات رياضية"]
  },
  {
    id: 'ksa-16',
    name: 'فن الكرة - Saudi Football Art',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/16sa.webp',
    region: 'ar',
    gender: 'men',
    category: 'Jersey',
    description: "تصميم يجمع بين ناطحات السحاب الحديثة والقلاع التاريخية مع لاعب يمثل الجيل الجديد.",
    metaTitle: "تيشيرت فن الكرة السعودية | الرياض بين الماضي والمستقبل | Folklore FC",
    metaDescription: "تيشيرت فن الكرة يروي قصة تطور الرياضة في المملكة. دمج مذهل بين ناطحات السحاب والتاريخ بأسلوب Streetwear عالمي.",
    altText: "تيشيرت أبيض يظهر تداخلاً فنياً بين قلعة المصمك وأبراج مركز الملك عبدالله المالي وكرة قدم.",
    keywords: ["فن الكرة", "تيشيرت الرياض", "ستريت وير سعودي عالمي", "تصميم جرافيك كرة قدم"]
  },

  // --- فرنسا الاحترافية (FR Men - SEO & AI Optimized) ---
  {
    id: 'fr-1',
    name: 'Gladiateur Moderne - Heritage Football Tee',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/1fr.webp',
    region: 'fr',
    gender: 'men',
    category: 'Jersey',
    description: "Fusion unique entre l'arène antique et le terrain moderne. Un casque de gladiateur sculpté dans l'âme du football.",
    metaTitle: "Maillot Gladiateur Moderne | Héritage Foot France | Folklore FC",
    metaDescription: "Le match est une bataille épique. Découvrez le maillot Gladiateur Moderne. Fusion unique entre histoire antique et football français. Style premium.",
    altText: "T-shirt gris avec un casque de gladiateur romain intégrant un ballon de football, style statue classique.",
    keywords: ["Maillot gladiateur", "Foot héritage", "T-shirt homme stylé", "France streetwear"]
  },
  {
    id: 'fr-2',
    name: 'Le Général - Tactique Football Tee',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/2fr.webp',
    region: 'fr',
    gender: 'men',
    category: 'Jersey',
    description: "Inspiré par Napoléon, ce design mêle cartographie tactique et esprit de leadership sur le terrain.",
    metaTitle: "Maillot Le Général | Tactique & Leadership Napoléon | Folklore FC",
    metaDescription: "Incarnez le leadership avec 'Le Général'. Un design inspiré par Napoléon Bonaparte mêlant tactique de guerre et football. Pour les capitaines.",
    altText: "Design de maillot avec portrait stylisé de Napoléon et schémas tactiques de football en arrière-plan.",
    keywords: ["Napoléon football", "Tactique foot design", "Maillot capitaine", "Leadership sportif"]
  },
  {
    id: 'fr-3',
    name: 'France Mode - Marinière 3D Football',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/3fr.webp',
    region: 'fr',
    gender: 'men',
    category: 'Jersey',
    description: "Un design minimaliste utilisant les rayures emblématiques de la marinière pour former un ballon de foot en 3D.",
    metaTitle: "Maillot Marinière Football | Style Parisien 3D | Folklore FC",
    metaDescription: "L'élégance à la française. Découvrez notre maillot Marinière revisité avec un effet 3D. Le mariage parfait entre mode parisienne et passion du foot.",
    altText: "T-shirt blanc avec rayures bleues horizontales formant un ballon de foot sphérique au centre.",
    keywords: ["Marinière football", "Mode Parisienne", "T-shirt foot chic", "Minimalisme français"]
  },
  {
    id: 'fr-4',
    name: 'Sang Froid - Alpes Football Edition',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/4fr.webp',
    region: 'fr',
    gender: 'men',
    category: 'Jersey',
    description: "Un ballon brisant la glace au sommet du Mont Blanc, symbolisant la précision et la puissance pure.",
    metaTitle: "Maillot Sang Froid | Mont Blanc Football Edition | Folklore FC",
    metaDescription: "Ne tremblez jamais devant le but. Le maillot Sang Froid célèbre la puissance des Alpes. Design glacé et précis pour les attaquants d'élite.",
    altText: "Ballon de football brisant un bloc de glace avec les sommets enneigés des Alpes en fond.",
    keywords: ["Mont Blanc foot", "Maillot hiver", "Puissance football", "Design Alpes"]
  },
  {
    id: 'fr-5',
    name: 'Révolution Street Art - Football Edition',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/5fr.webp',
    region: 'fr',
    gender: 'men',
    category: 'Jersey',
    description: "Inspiré par l'art urbain, ce design transforme le fumigène tricolore en une célébration passionnée.",
    metaTitle: "Maillot Révolution Street Art | Culture Ultra France | Folklore FC",
    metaDescription: "L'esprit de la rue rencontre le stade. Maillot Révolution inspiré par le street art français et la ferveur des ultras. Vivez la passion tricolore.",
    altText: "Silhouette d'un supporter lançant un fumigène avec de la fumée bleue, blanche et rouge style graffiti.",
    keywords: ["Street art foot", "Ultra France", "Maillot révolution", "Graffiti football"]
  },
  {
    id: 'fr-6',
    name: 'Coq Royal - Allez Les Bleus Edition',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/6fr.webp',
    region: 'fr',
    gender: 'men',
    category: 'Jersey',
    description: "Le Coq Gaulois réinventé avec une élégance moderne et des motifs royaux tricolores.",
    metaTitle: "Maillot Coq Royal | Allez Les Bleus Heritage | Folklore FC",
    metaDescription: "Portez fièrement le symbole national. Le Coq Royal allie motifs baroques et fierté tricolore. Une pièce de collection indispensable.",
    altText: "Emblème majestueux d'un coq bleu avec dorures royales sur un ballon de foot classique.",
    keywords: ["Coq Gaulois", "Allez les bleus", "Maillot France royal", "Fierté nationale"]
  },
  {
    id: 'fr-7',
    name: 'Le Gardien Gothique - Notre-Dame Pitch Tee',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/7fr.webp',
    region: 'fr',
    gender: 'men',
    category: 'Jersey',
    description: "Inspiré par l'architecture gothique de Paris, plaçant une gargouille protectrice sur la cage de but.",
    metaTitle: "Maillot Gardien Gothique | Architecture Paris Foot | Folklore FC",
    metaDescription: "L'invincibilité du gardien. Design inspiré des gargouilles de Notre-Dame protégeant les cages. Style sombre et sophistiqué pour l'éternité.",
    altText: "Illustration d'une gargouille en pierre accroupie sur un filet de but de football, style gothique parisien.",
    keywords: ["Notre-Dame foot", "Style gothique Paris", "Maillot gardien", "Architecture maillot"]
  },
  {
    id: 'fr-8',
    name: 'Le Tacticien - Rodin Thinking Football',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/8fr.webp',
    region: 'fr',
    gender: 'men',
    category: 'Jersey',
    description: "Le Penseur de Rodin devient l'entraîneur ultime, méditant sur un ballon de pierre au milieu des schémas.",
    metaTitle: "Maillot Le Tacticien Rodin | Intelligence du Jeu | Folklore FC",
    metaDescription: "L'art rencontre le génie stratégique. Découvrez Le Tacticien, inspiré par Rodin. Un hommage à la réflexion nécessaire pour dominer le football.",
    altText: "Statue du Penseur de Rodin assis sur un ballon de foot géant réfléchissant à une tactique.",
    keywords: ["Rodin football", "Le Penseur maillot", "Tactique stratégique", "Art & Foot France"]
  },
  {
    id: 'fr-9',
    name: 'Service de Classe - Art Déco Football',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/9fr.webp',
    region: 'fr',
    gender: 'men',
    category: 'Jersey',
    description: "L'art de la passe décisive servi sur un plateau d'argent, inspiré par le raffinement de l'époque Art Déco.",
    metaTitle: "Maillot Service de Classe | Art Déco & Élégance Foot | Folklore FC",
    metaDescription: "La classe pure sur le terrain. Un design Art Déco célébrant la précision de la passe décisive. Élégance française et style premium.",
    altText: "Design géométrique art déco avec un serveur portant un ballon de foot comme un plat de luxe.",
    keywords: ["Art Déco football", "Élégance foot homme", "Passe décisive", "Luxury streetwear"]
  },
  {
    id: 'fr-10',
    name: "Le Buteur - L'Alchimiste du Football",
    price: 39.99,
    currency: 'USD',
    image: '/images/men/10fr.webp',
    region: 'fr',
    gender: 'men',
    category: 'Jersey',
    description: "Une carte de tarot mystique où le buteur incarne l'alchimiste capable de transformer chaque occasion en or.",
    metaTitle: "Maillot Tarot Le Buteur | L'Alchimie du But | Folklore FC",
    metaDescription: "Le destin est entre vos pieds. Maillot Buteur inspiré du tarot divinatoire. Transformez chaque occasion en or avec ce design mystique.",
    altText: "Carte de tarot stylisée 'Le Buteur' avec des symboles alchimiques et un ballon doré.",
    keywords: ["Tarot football", "Alchimiste foot", "Maillot mystique", "Design ésotérique"]
  },
  {
    id: 'fr-11',
    name: 'Immortels - Catacombes Heritage Edition',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/11fr.webp',
    region: 'fr',
    gender: 'men',
    category: 'Jersey',
    description: "Fusion entre l'esthétique des catacombes de Paris et des ballons vintage pour une passion éternelle.",
    metaTitle: "Maillot Immortels Paris | Catacombes Heritage | Folklore FC",
    metaDescription: "Une passion qui traverse les siècles. Découvrez le design Immortels fusionnant l'histoire sombre de Paris avec la culture foot vintage. Style grunge.",
    altText: "T-shirt avec crânes stylisés disposés en forme de ballon de foot, ambiance catacombes de Paris.",
    keywords: ["Catacombes Paris foot", "Style grunge homme", "Football éternel", "Maillot sombre"]
  },
  // --- إسبانيا الاحترافية (ES Men - SEO & AI Optimized) ---
  {
    id: 'es-1',
    name: 'Armada Invencible - Edición Herencia',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/1es.webp',
    region: 'es',
    gender: 'men',
    category: 'Jersey',
    description: "La historia se encuentra con el campo. El legendario galeón 'Armada Invencible' reinventado, lanzando balones de fútbol.",
    metaTitle: "Camiseta Armada Invencible | Herencia Fútbol España | Folklore FC",
    metaDescription: "Domina el campo con la Edición Herencia. Diseño inspirado en la Armada Invencible y la gloria marítima de España. Calidad premium para hombres.",
    altText: "Galeón español histórico lanzando balones de fútbol desde sus cañones, estilo grabado antiguo sobre camiseta premium.",
    keywords: ["Armada Invencible fútbol", "Camiseta herencia España", "Moda urbana hombre", "Galeón español jersey"]
  },
  {
    id: 'es-2',
    name: 'El Gigante - Dominio Absoluto',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/2es.webp',
    region: 'es',
    gender: 'men',
    category: 'Jersey',
    description: "Dominando las montañas como una leyenda. Una silueta imponente que representa el impacto masivo del fútbol español.",
    metaTitle: "Camiseta El Gigante | Dominio Absoluto Fútbol | Folklore FC",
    metaDescription: "Representa la fuerza del fútbol español con 'El Gigante'. Un diseño imponente para hombres que dominan el juego con pasión y presencia.",
    altText: "Silueta gigante de un futbolista sobre montañas españolas bajo un sol radiante de victoria.",
    keywords: ["Camiseta gigante fútbol", "Dominio absoluto España", "Streetwear hombre", "Diseño épico fútbol"]
  },
  {
    id: 'es-3',
    name: 'Maestro - Control del Matador',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/3es.webp',
    region: 'es',
    gender: 'men',
    category: 'Jersey',
    description: "El arte del control total. Un matador dominando el balón con su capote, simbolizando la elegancia y precisión técnica.",
    metaTitle: "Camiseta Maestro Matador | Control y Elegancia Fútbol | Folklore FC",
    metaDescription: "Domina el balón como un maestro. Diseño inspirado en la elegancia del matador y el genio técnico de los mediocampistas españoles.",
    altText: "Matador de toros usando su capote rojo para controlar un balón de fútbol con estilo artístico.",
    keywords: ["Maestro fútbol", "Control del balón", "Estilo matador", "Camiseta técnica elegante"]
  },
  {
    id: 'es-4',
    name: 'Sangre y Arena - Pasión Flamenca',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/4es.webp',
    region: 'es',
    gender: 'men',
    category: 'Jersey',
    description: "El corazón de España en un diseño. Fusión entre la fuerza del toro bravío, el ritmo del flamenco y la garra del jugador.",
    metaTitle: "Camiseta Sangre y Arena | Pasión y Furia Roja | Folklore FC",
    metaDescription: "La esencia pura de España. Fusión de toro, flamenco y fútbol en el diseño 'Sangre y Arena'. Siente la garra de la Furia Roja.",
    altText: "Diseño vibrante que combina un toro bravo, una guitarra de flamenco y un futbolista en acción.",
    keywords: ["Sangre y Arena fútbol", "Furia Roja", "Cultura española hombre", "Camiseta pasión flamenca"]
  },
  {
    id: 'es-5',
    name: 'Espíritu de Barcelona - Mosaico Gaudí',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/5es.webp',
    region: 'es',
    gender: 'men',
    category: 'Jersey',
    description: "Un tributo a la ciudad del arte y el fútbol. Inspirado en el estilo de Gaudí, combina la Sagrada Família y el Arco del Triunfo.",
    metaTitle: "Camiseta Espíritu de Barcelona | Arte Gaudí Fútbol | Folklore FC",
    metaDescription: "Homenaje a Barcelona y Gaudí. Camiseta con diseño de mosaico modernista que celebra la herencia cultural de la ciudad condal.",
    altText: "Mosaico estilo Gaudí representando la Sagrada Família y elementos icónicos de Barcelona con un balón central.",
    keywords: ["Barcelona fútbol", "Gaudí mosaico", "Moda urbana Barcelona", "Arquitectura y fútbol"]
  },
  {
    id: 'es-6',
    name: 'Leyenda Imperial - Escudo Real',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/6es.webp',
    region: 'es',
    gender: 'men',
    category: 'Jersey',
    description: "Lleva el legado de los campeones. Un escudo magistral que une la ornamentación real con el espíritu del juego moderno.",
    metaTitle: "Camiseta Leyenda Imperial | Escudo Real Fútbol | Folklore FC",
    metaDescription: "Juega con nobleza y coraje. El diseño Leyenda Imperial fusiona la heráldica real con la pasión del fútbol moderno para hombres.",
    altText: "Escudo heráldico imperial ornamentado con motivos de fútbol y coronas reales sobre fondo oscuro.",
    keywords: ["Leyenda Imperial", "Escudo real fútbol", "Nobleza deportiva", "Camiseta premium hombre"]
  },
  {
    id: 'es-7',
    name: 'Furia Geométrica - España Abstracta',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/7es.webp',
    region: 'es',
    gender: 'men',
    category: 'Jersey',
    description: "El arte moderno se encuentra con la tradición. Una representación geométrica del jugador, el toro y la guitarra española.",
    metaTitle: "Camiseta Furia Geométrica | Arte Abstracto Español | Folklore FC",
    metaDescription: "Vanguardia y tradición. Un diseño abstracto y geométrico que celebra la cultura polifacética de España en el campo de juego.",
    altText: "Composición geométrica abstracta con formas de toro, guitarra y futbolista en colores rojo y amarillo.",
    keywords: ["Arte abstracto fútbol", "Geometría española", "Streetwear vanguardista", "Diseño cultural moderno"]
  },
  {
    id: 'es-8',
    name: 'Arte y Gol - Edición Surrealista',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/8es.webp',
    region: 'es',
    gender: 'men',
    category: 'Jersey',
    description: "Donde el fútbol se convierte en arte eterno. Inspirado en Dalí, con un balón fundiéndose sobre la portería.",
    metaTitle: "Camiseta Arte y Gol Dalí | Fútbol Surrealista | Folklore FC",
    metaDescription: "El fútbol es una obra maestra. Camiseta inspirada en el genio de Salvador Dalí con estética surrealista. Para los que ven más allá del juego.",
    altText: "Balón de fútbol fundiéndose al estilo de los relojes de Dalí sobre un poste de portería en un paisaje desértico.",
    keywords: ["Salvador Dalí fútbol", "Surrealismo deportivo", "Arte eterno", "Camiseta coleccionista"]
  },
  {
    id: 'es-9',
    name: 'Sagrada Pasión - Herencia de Sevilla',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/9es.webp',
    region: 'es',
    gender: 'men',
    category: 'Jersey',
    description: "El fútbol es una fe en España. Diseño que rinde homenaje a la cultura de la Semana Santa sevillana.",
    metaTitle: "Camiseta Sagrada Pasión | Herencia de Sevilla | Folklore FC",
    metaDescription: "La unión de fe y fútbol. Camiseta inspirada en la Semana Santa de Sevilla. Un tributo a la tradición espiritual y el fervor del estadio.",
    altText: "Iconografía de estilo sacro sevillano rodeando un balón de fútbol con detalles de orfebrería dorada.",
    keywords: ["Semana Santa Sevilla", "Pasión sagrada fútbol", "Cultura andaluza", "Diseño religioso deportivo"]
  },
  {
    id: 'es-10',
    name: 'La Furia - Explosión Nacional',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/10es.webp',
    region: 'es',
    gender: 'men',
    category: 'Jersey',
    description: "Siente la energía indomable de la selección. Un mapa de España que estalla en color con un impacto de balón.",
    metaTitle: "Camiseta La Furia Explosión | Energía Selección España | Folklore FC",
    metaDescription: "Pasión vibrante en cada fibra. Mapa de España con explosión de colores nacionales. Representa el fútbol dinámico de la selección española.",
    altText: "Mapa de España con una explosión central de pintura roja y amarilla causada por un balón de fútbol.",
    keywords: ["La Furia España", "Camiseta selección española", "Explosión nacional", "Moda deportiva vibrante"]
  },
  {
    id: 'es-11',
    name: 'Valor - Leyenda del Estadio',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/11es.webp',
    region: 'es',
    gender: 'men',
    category: 'Jersey',
    description: "Inspirado en el coraje histórico, celebra la valentía necesaria para conquistar la gloria.",
    metaTitle: "Camiseta Valor Leyenda | Coraje Histórico Fútbol | Folklore FC",
    metaDescription: "Inspirada en los héroes históricos de España. Un diseño que celebra la valentía y el honor en el terreno de juego. Para campeones.",
    altText: "Caballero español a caballo con bandera nacional frente a un gran estadio de fútbol clásico.",
    keywords: ["Valor fútbol", "Leyenda del estadio", "Honor español", "Camiseta épica hombre"]
  },
  {
    id: 'es-12',
    name: 'Mosaico de Pasión - La Furia Roja',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/12es.webp',
    region: 'es',
    gender: 'men',
    category: 'Jersey',
    description: "Un collage dinámico que captura la esencia del país: Gaudí, el toro y la técnica del jugador.",
    metaTitle: "Camiseta Mosaico de Pasión | Esencia Furia Roja | Folklore FC",
    metaDescription: "Toda España en una imagen. Collage dinámico con elementos de Gaudí, el toro bravo y la técnica futbolística. Streetwear de impacto.",
    altText: "Collage artístico con cabeza de toro, patrones de Gaudí y siluetas de futbolistas en colores nacionales.",
    keywords: ["Mosaico de pasión", "Furia Roja streetwear", "Iconos españoles", "Diseño collage fútbol"]
  },
  {
    id: 'es-13',
    name: 'Toro Sagrado - Edición Tradicional',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/13es.webp',
    region: 'es',
    gender: 'men',
    category: 'Jersey',
    description: "El toro, símbolo de poder, decorado con patrones tradicionales españoles sobre el fondo de un estadio.",
    metaTitle: "Camiseta Toro Sagrado | Poder Tradicional Fútbol | Folklore FC",
    metaDescription: "Fuerza y tradición. El icónico toro español decorado con patrones clásicos. Un diseño que une el espíritu de la arena con el césped.",
    altText: "Cabeza de toro decorada con patrones ornamentales españoles sobre fondo de luces de estadio.",
    keywords: ["Toro sagrado", "Símbolo de poder", "Patrones tradicionales", "Streetwear España premium"]
  },
  {
    id: 'es-14',
    name: 'Olé el Fútbol - Estilo Clásico',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/14es.webp',
    region: 'es',
    gender: 'men',
    category: 'Jersey',
    description: "La elegancia del matador aplicada al balón vintage. Cada toque es arte y cada pase es un poema.",
    metaTitle: "Camiseta Olé el Fútbol | Estilo Clásico y Arte | Folklore FC",
    metaDescription: "Puro arte español. Camiseta que celebra la 'faena' perfecta del mediocampista con estilo clásico y vintage. Olé por el buen fútbol.",
    altText: "Balón de fútbol vintage con una montera de torero encima y salpicaduras de arte clásico.",
    keywords: ["Olé el fútbol", "Estilo clásico español", "Arte y fútbol", "Camiseta vintage hombre"]
  },
  // --- أمريكا الاحترافية (EN Men - SEO & AI Optimized) ---
  {
    id: 'us-1',
    name: 'Native Warrior - First Pitch Legacy',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/1us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "Honoring the ancestral strength and spiritual connection to the land. This design blends Native American warrior heritage with the competitive drive of modern soccer.",
    metaTitle: "Native Warrior Soccer Jersey | Indigenous Heritage Kit | Folklore FC",
    metaDescription: "Honor the guardians of the field with the Native Warrior jersey. A powerful blend of ancestral strength and modern soccer performance. Shop the legacy.",
    altText: "Native American warrior with traditional headdress merged with a soccer ball, vintage artistic style on a white t-shirt.",
    keywords: ["Native American soccer", "Heritage jersey", "Indigenous sports apparel", "Warrior spirit football"]
  },
  {
    id: 'us-2',
    name: 'Steel Trap - Unbreakable Defense',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/2us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "For the defenders who leave nothing to chance. Inspired by the rugged grit of the American frontier, symbolizing an impenetrable backline.",
    metaTitle: "Steel Trap Defense Jersey | Unbreakable Soccer Gear | Folklore FC",
    metaDescription: "Shut down the opposition with the Steel Trap jersey. Inspired by the grit of the American frontier. Perfect for the defenders who dominate the pitch.",
    altText: "Mechanical steel trap with a soccer ball inside, rustic and rugged aesthetic on a dark men's jersey.",
    keywords: ["Defensive soccer shirt", "American frontier style", "Rugged sportswear", "Steel Trap football"]
  },
  {
    id: 'us-3',
    name: 'Rodeo Soul - Ride the Game',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/3us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "Catch the spirit of the Wild West. Combining the thrill of the rodeo with the passion of the pitch, featuring a cowboy taming the beautiful game.",
    metaTitle: "Rodeo Soul Cowboy Jersey | Wild West Soccer Apparel | Folklore FC",
    metaDescription: "Ride the game with Rodeo Soul. A unique fusion of rodeo thrill and soccer passion. Built for the fearless who stay on top of the pitch.",
    altText: "Cowboy riding a bucking soccer ball like a rodeo bronco, classic western illustration style.",
    keywords: ["Cowboy soccer", "Rodeo sports shirt", "Wild West streetwear", "American rodeo football"]
  },
  {
    id: 'us-4',
    name: 'Timber! - The Hard Work Tee',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/4us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "Dedicated to the grind and the hustle. Inspired by legendary lumberjacks, representing raw power and relentless effort.",
    metaTitle: "Timber! Lumberjack Soccer Jersey | Hard Work & Hustle | Folklore FC",
    metaDescription: "Chop down the competition. The Timber! jersey celebrates the relentless grind of American lumberjacks. For players who value hard work and power.",
    altText: "Lumberjack axe embedded in a wooden soccer ball with wood chips flying, vintage industrial style.",
    keywords: ["Lumberjack sports apparel", "Work ethic soccer", "Hard work tee", "American grit streetwear"]
  },
  {
    id: 'us-5',
    name: 'Patriot Warrior - Running to Glory',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/5us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "A powerful fusion of national pride and indigenous heritage. Representing the speed and pursuit of excellence in American soccer.",
    metaTitle: "Patriot Warrior USA Jersey | Stars & Stripes Football | Folklore FC",
    metaDescription: "Run to glory with the Patriot Warrior. A fusion of indigenous heritage and American pride. High-impact design for the elite athlete.",
    altText: "Indigenous warrior in full stride against a backdrop of stars and stripes, patriotic soccer theme.",
    keywords: ["USA patriotic soccer", "Warrior football jersey", "American pride sports", "Stars and stripes kit"]
  },
  {
    id: 'us-6',
    name: 'Frontier Archer - Precision Strike',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/6us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "Focus, aim, and execute. Celebrating the mastery of the frontier bowman, translating precision to the perfect strike.",
    metaTitle: "Frontier Archer Soccer Shirt | Precision Strike Gear | Folklore FC",
    metaDescription: "Never miss the mark. The Frontier Archer jersey is designed for clinical finishers who value the precision of the legendary American bowman.",
    altText: "Native American archer aiming at a goal, precision-themed graphic on a white men's soccer t-shirt.",
    keywords: ["Precision strike football", "Archer soccer design", "Clinical finisher gear", "Frontier sports"]
  },
  {
    id: 'us-7',
    name: 'Western Legacy - Desert Gold Kick',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/7us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "Where the dust of the desert meets the green of the goal. Cowboy-inspired design celebrating the historic legacy of the frontier.",
    metaTitle: "Western Legacy Soccer Jersey | Desert Gold Edition | Folklore FC",
    metaDescription: "Step into the boots of a legend. The Western Legacy jersey brings the rugged spirit of the desert to the modern soccer pitch. Vintage gold style.",
    altText: "Cowboy boots kicking a golden soccer ball in a desert landscape, sepia-toned vintage aesthetic.",
    keywords: ["Western soccer legacy", "Desert football shirt", "Cowboy boots sports", "Vintage Americana"]
  },
  {
    id: 'us-8',
    name: 'Ghost Rider USA - Spirit of Vengeance',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/8us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "Unleash the heat of the road. A high-octane tribute to the rebellious American spirit, featuring a flaming skeleton.",
    metaTitle: "Ghost Rider Soccer Jersey | Flaming Skeleton USA | Folklore FC",
    metaDescription: "Play with burning passion. The Ghost Rider USA jersey is a tribute to the rebel spirit. High-octane design for players who ignite the pitch.",
    altText: "Flaming skeleton riding a motorcycle with soccer ball wheels, dark and rebellious motorcycle club aesthetic.",
    keywords: ["Ghost Rider football", "Rebel soccer jersey", "Biker style sports", "Flaming skeleton shirt"]
  },
  {
    id: 'us-9',
    name: 'Wanted for Pyro - Outlaw Spirit',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/9us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "Inspired by the rebellious energy of the stands. Features a Wild West outlaw lighting up the pitch with passion.",
    metaTitle: "Wanted for Pyro Jersey | Outlaw Soccer Supporter | Folklore FC",
    metaDescription: "For the supporters who live for the heat. The Wanted for Pyro jersey combines Wild West outlaw vibes with modern stadium passion.",
    altText: "Vintage 'Wanted' poster of a cowboy holding a flare in a soccer stadium, gritty outlaw style.",
    keywords: ["Soccer pyro shirt", "Outlaw football gear", "Ultra culture USA", "Wild West supporter"]
  },
  {
    id: 'us-10',
    name: 'Uncle Sam - The Soccer Legend',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/10us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "The ultimate recruitment for your squad. Uncle Sam swaps his recruitment poster for a legendary strike.",
    metaTitle: "Uncle Sam Soccer Jersey | All-American Legend | Folklore FC",
    metaDescription: "I want YOU to win. Uncle Sam reimagined as a soccer legend. A classic American icon for the modern football culture. Join the squad.",
    altText: "Uncle Sam in his classic hat performing a bicycle kick, parody of the recruitment poster.",
    keywords: ["Uncle Sam soccer", "All-American football", "Iconic US sports shirt", "Patriotic soccer tee"]
  },
  {
    id: 'us-11',
    name: 'Lethal Defense - Diamondback Strike',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/11us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "Sharp, fast, and dangerous. Inspired by the Mojave Desert's apex predator, representing an impenetrable defense.",
    metaTitle: "Diamondback Soccer Jersey | Lethal Defense Mojave | Folklore FC",
    metaDescription: "Strike when they least expect it. The Diamondback jersey represents the lethal precision of the Mojave predator. Impenetrable defense gear.",
    altText: "Rattlesnake coiled around a soccer ball, desert-themed dark graphic on men's t-shirt.",
    keywords: ["Rattlesnake soccer", "Mojave sports apparel", "Aggressive defense shirt", "Desert predator jersey"]
  },
  {
    id: 'us-12',
    name: 'Hard Hitting FC - Knockout Edition',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/12us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "Where the ring meets the pitch. Celebrating the grit of American boxing, for strikers who play with heavy intensity.",
    metaTitle: "Hard Hitting FC Jersey | Boxing Inspired Football | Folklore FC",
    metaDescription: "Deliver the total knockout. For strikers who play with the intensity of an American boxer. Grit, power, and high-impact style.",
    altText: "Boxing gloves holding a soccer ball with a 'KO' stamp, industrial vintage boxing gym aesthetic.",
    keywords: ["Boxing soccer shirt", "Hard hitting football", "Combat sports streetwear", "Knockout edition jersey"]
  },
  {
    id: 'us-13',
    name: 'Native Pride - Heritage Bicycle Kick',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/13us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "A breathtaking bicycle kick fused with indigenous warrior aesthetics, honoring the roots of American athleticism.",
    metaTitle: "Native Pride Bicycle Kick Jersey | Heritage Sports Art | Folklore FC",
    metaDescription: "Honoring the original guardians. The Native Pride jersey features a breathtaking bicycle kick in a warrior aesthetic. Deep roots, soaring spirit.",
    altText: "Indigenous athlete performing a bicycle kick with feathers and traditional patterns trailing, high-art style.",
    keywords: ["Native American bicycle kick", "Heritage sports art", "Indigenous pride jersey", "Athletic warrior shirt"]
  },
  {
    id: 'us-14',
    name: 'Heavy Artillery - Long Range Cannon',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/14us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "For the players with explosive power. Inspired by historic American artillery, symbolizing long-range strikers.",
    metaTitle: "Heavy Artillery Soccer Shirt | Long Range Striker | Folklore FC",
    metaDescription: "Unleash thunderous shots. The Heavy Artillery jersey is built for long-range strikers. Inspired by historic American power and precision.",
    altText: "Vintage American cannon firing a soccer ball, smoke and fire effects, industrial grey shirt.",
    keywords: ["Long range strike", "Artillery soccer", "Explosive power football", "Historic US military style"]
  },
  {
    id: 'us-15',
    name: 'Liberty Pitch - Coast to Coast',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/15us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "A grand celebration of American landmarks from the Golden Gate to the Statue of Liberty.",
    metaTitle: "Liberty Pitch USA Jersey | Coast to Coast Landmarks | Folklore FC",
    metaDescription: "Unite under one flag. The Liberty Pitch jersey celebrates iconic American landmarks from coast to coast. A tribute to US football culture.",
    altText: "Collage of US landmarks like the Golden Gate Bridge and Statue of Liberty with a central soccer ball.",
    keywords: ["USA landmarks soccer", "Coast to coast football", "American heritage jersey", "National pride shirt"]
  },
  {
    id: 'us-16',
    name: 'Revolutionary Squad - 1776 Pitch',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/16us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "Lead the charge on the field. Inspired by the founding spirit of 1776, for the captains and leaders.",
    metaTitle: "1776 Revolutionary Soccer Jersey | Founding Spirit Gear | Folklore FC",
    metaDescription: "Lead your squad to victory. Inspired by the spirit of 1776. For the captains who fight for every inch of the pitch. Join the revolution.",
    altText: "Revolutionary War soldier with a soccer ball, vintage parchment style with 1776 typography.",
    keywords: ["1776 soccer shirt", "Revolutionary football", "Founding fathers sports", "Captain's jersey USA"]
  },
  {
    id: 'us-17',
    name: 'Forged in Steel - Industrial Grit Tee',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/17us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "Celebrating the industrial heart of America, where every goal is forged through heat and hard work.",
    metaTitle: "Forged in Steel Soccer Jersey | Industrial Work Ethic | Folklore FC",
    metaDescription: "Success is earned. The Forged in Steel jersey celebrates the American industrial heartland. For players with a blue-collar work ethic.",
    altText: "Molten steel being poured into a soccer ball mold, industrial factory setting, dark metallic colors.",
    keywords: ["Industrial soccer", "Blue collar football", "Hard work sports gear", "Forged in steel shirt"]
  },
  {
    id: 'us-18',
    name: 'Iron Horse - Full Steam Ahead',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/18us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "Unstoppable momentum. Inspired by the legendary American steam locomotives that built the nation.",
    metaTitle: "Iron Horse Locomotive Jersey | Unstoppable Momentum | Folklore FC",
    metaDescription: "Full steam ahead. The Iron Horse jersey represents the power of American locomotives. Drive through the opposition with pure momentum.",
    altText: "Steam train engine Charging forward with a soccer ball as the headlight, vintage steam engine aesthetic.",
    keywords: ["Locomotive soccer", "Iron Horse football", "Unstoppable momentum", "Vintage train sports"]
  },
  {
    id: 'us-19',
    name: 'The Hitman - Clinical Finisher',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/19us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "Silent, precise, and lethal. 'The Hitman' symbolizes the artistic precision of a striker who needs only one shot.",
    metaTitle: "The Hitman Soccer Jersey | Clinical Finisher Style | Folklore FC",
    metaDescription: "One shot, one goal. The Hitman jersey is for the precise strikers. Artistic precision meets lethal finishing. Pure class in every strike.",
    altText: "Violin case holding a golden soccer ball and clinical finishing tools, 1920s mobster aesthetic.",
    keywords: ["The Hitman soccer", "Clinical finisher shirt", "Precise striker jersey", "Classy football apparel"]
  },
  {
    id: 'us-20',
    name: 'Soccer Slam - All-American Wrestler',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/20us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "Where entertainment meets athleticism. Celebrating the high-flying energy of American pro-wrestling.",
    metaTitle: "Soccer Slam Wrestling Jersey | All-American Showman | Folklore FC",
    metaDescription: "Dominate the arena. The Soccer Slam jersey celebrates the energy of American pro-wrestling. For the showmen who play with patriotic flair.",
    altText: "Wrestler in a mask holding a soccer ball above his head in a stadium ring, bright patriotic colors.",
    keywords: ["Wrestling soccer", "All-American showman", "Pro-wrestling football", "High-energy sports shirt"]
  },
  {
    id: 'us-21',
    name: 'Game Over - Street Rebel Edition',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/21us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "Inspired by the 1950s American greaser subculture. A gritty, back-alley design for the rebellious spirit.",
    metaTitle: "Game Over Greaser Jersey | Street Rebel Soccer | Folklore FC",
    metaDescription: "It's game over for the rest. Inspired by the 1950s rebel culture. Gritty streetwear for the players who own the back-alley pitch.",
    altText: "Rebellious 50s greaser leaning against a brick wall holding a soccer ball, gritty black and white style.",
    keywords: ["Greaser soccer", "Street rebel football", "50s Americana shirt", "Rebellious sports gear"]
  },
  {
    id: 'us-22',
    name: 'Canyon Kickoff - Wild West Legacy',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/22us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "Mastering the frontier. A cowboy taming a bucking bronco while delivering a legendary kick across the canyon.",
    metaTitle: "Canyon Kickoff Western Jersey | Frontier Mastery | Folklore FC",
    metaDescription: "Tame the frontier. The Canyon Kickoff jersey celebrates the fearless spirit of the West. A legendary kick across the desert canyons.",
    altText: "Cowboy kicking a ball across a deep red rock canyon, cinematic Wild West landscape.",
    keywords: ["Canyon soccer", "Western kickoff shirt", "Grand Canyon sports", "Wild West football"]
  },
  {
    id: 'us-23',
    name: 'Minutemen FC - Revolutionary Spirit',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/23us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "Ready at a minute's notice. Honoring the colonial soldiers, blending the Liberty Bell with the modern stadium.",
    metaTitle: "Minutemen FC Soccer Jersey | Revolutionary Spirit | Folklore FC",
    metaDescription: "Ready for the call. The Minutemen FC jersey honors American leadership and sacrifice. Blending history with the modern stadium.",
    altText: "Liberty Bell with a soccer ball as the clapper, colonial soldier silhouette in the background.",
    keywords: ["Minutemen soccer", "Liberty Bell football", "Revolutionary War shirt", "US history sports"]
  },
  {
    id: 'us-24',
    name: 'Storm the Pitch - Tornado Force',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/24us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "Nature's unstoppable fury. Capturing the raw energy of a Great Plains tornado swirling around the goal.",
    metaTitle: "Tornado Force Soccer Jersey | Great Plains Storm | Folklore FC",
    metaDescription: "Bring the chaos. The Storm the Pitch jersey captures the whirlwind speed of a Great Plains tornado. Unstoppable energy gear.",
    altText: "Massive tornado made of soccer balls swirling over a green pitch with a dramatic sky.",
    keywords: ["Tornado soccer", "Storm the pitch jersey", "Whirlwind speed football", "Nature force sports"]
  },
  {
    id: 'us-25',
    name: 'Power Play - Buffalo Charge Tee',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/25us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "Pure, unstoppable force. Featuring the American Bison charging through the net, symbolizing resilience.",
    metaTitle: "Buffalo Charge Power Jersey | American Resilience | Folklore FC",
    metaDescription: "Break through every barrier. The Buffalo Charge jersey symbolizes the raw power and resilience of the American spirit on the pitch.",
    altText: "American Bison charging through a soccer net, woodcut style illustration.",
    keywords: ["Buffalo soccer jersey", "Resilience football shirt", "Bison charge sports", "American force gear"]
  },
  {
    id: 'us-26',
    name: 'Bronco Ball - Cowboy Legacy Edition',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/26us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "Taming the game. This creative design features a cowboy riding a soccer ball like a bucking bronco.",
    metaTitle: "Bronco Ball Western Jersey | Cowboy Legacy Edition | Folklore FC",
    metaDescription: "Tame the game under the stars. The Bronco Ball jersey is a unique fusion of rodeo thrill and football passion. Cowboy legacy gear.",
    altText: "Cowboy riding a giant soccer ball like a bucking bronco under a starry night sky.",
    keywords: ["Bronco soccer", "Cowboy football jersey", "Rodeo legacy shirt", "Western sports art"]
  },
  {
    id: 'us-27',
    name: 'Liberty Kick - Revolutionary Legacy',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/27us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "Freedom to play. A colonial soldier delivers a legendary bicycle kick in front of the Liberty Bell.",
    metaTitle: "Liberty Kick Soccer Jersey | Revolutionary Legacy | Folklore FC",
    metaDescription: "Celebrate the evolution of US soccer. The Liberty Kick jersey features a historic bicycle kick by a colonial soldier. Freedom to win.",
    altText: "Colonial soldier performing a bicycle kick with the Liberty Bell in the background, blue and white theme.",
    keywords: ["Liberty kick soccer", "Revolutionary legacy gear", "Colonial sports shirt", "Bicycle kick art"]
  },
  {
    id: 'us-28',
    name: 'Desert Striker - Longhorn Heritage',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/28us.webp',
    region: 'en',
    gender: 'men',
    category: 'Jersey',
    description: "The soul of the Southwest. Featuring the iconic Longhorn skull and a frontier striker, honoring the rugged landscapes.",
    metaTitle: "Desert Striker Longhorn Jersey | Southwest Heritage | Folklore FC",
    metaDescription: "The soul of the Southwest. The Desert Striker jersey pays tribute to the rugged landscapes and the historic legacy of Western soccer.",
    altText: "Longhorn skull with a soccer ball between its horns, desert frontier background.",
    keywords: ["Longhorn soccer jersey", "Southwest sports shirt", "Desert striker gear", "Western heritage football"]
  },
  
  // --- اليابان الاحترافية (JA Men - SEO & AI Optimized) ---
  {
    id: 'jp-1',
    name: 'Shadow Striker - Shinobi Edition',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/1ja.webp',
    region: 'ja',
    gender: 'men',
    category: 'Jersey',
    description: "ステルスと精度の融合。'シャドウ・ストライカー'は、忍者の俊敏さと現代サッカーの戦術を組み合わせたデザインです。影の中からゴールを狙う、ストリートウェアの真髄を体感してください。",
    metaTitle: "忍者 サッカーユニフォーム | Shadow Striker Shinobi | Folklore FC",
    metaDescription: "忍者の俊敏さとサッカー戦術の融合。'シャドウ・ストライカー'限定エディション。影からゴールを狙うストライカーのための究極のストリートウェア。",
    altText: "忍者の装束をモチーフにしたスタイリッシュなサッカーユニフォーム、背後に手裏剣のグラフィック。",
    keywords: ["忍者 サッカー", "Shinobi Jersey", "ストリートウェア 日本", "忍者 デザイン Tシャツ"]
  },
  {
    id: 'jp-2',
    name: 'Tokyo FC 2077 - Cyberpunk Pitch',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/2ja.webp',
    region: 'ja',
    gender: 'men',
    category: 'Jersey',
    description: "ネオ東京の未来を纏う。サイバーパンクな美学とサッカー文化が交差する'Tokyo FC 2077'。次世代のフットボールスタイルを切り拓きます。",
    metaTitle: "サイバーパンク サッカーシャツ | Tokyo FC 2077 | Folklore FC",
    metaDescription: "未来の東京を歩く。サイバーパンク美学とフットボールの融合。Tokyo FC 2077で、ネオン輝くストリートスタイルを手に入れろ。",
    altText: "ネオンカラーの回路図が描かれたサイバーパンク風サッカーユニフォーム、東京の夜景をイメージ。",
    keywords: ["サイバーパンク ファッション", "東京 FC", "Cyberpunk Soccer", "ネオン デザイン シャツ"]
  },
  {
    id: 'jp-3',
    name: 'Blue Samurai - Kabuto Heritage',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/3ja.webp',
    region: 'ja',
    gender: 'men',
    category: 'Jersey',
    description: "侍の魂、ピッチに降臨。伝統的な兜（かぶと）に葛飾北斎の波の文様を刻んだデザイン。日本の伝統とサッカーの情熱が融合した一着。",
    metaTitle: "侍 サッカーユニフォーム | Blue Samurai Kabuto | Folklore FC",
    metaDescription: "侍の魂を纏う。伝統的な兜と北斎の波をデザインしたBlue Samurai。日本の誇りと情熱をピッチで表現するためのプレミアムシャツ。",
    altText: "侍の兜と力強い波の文様が融合した紺色のサッカーユニフォーム、和柄のディテール。",
    keywords: ["侍 ユニフォーム", "Blue Samurai", "和柄 サッカー", "日本伝統 スポーツウェア"]
  },
  {
    id: 'jp-4',
    name: 'The Art of Kick - Kanji Spirit Tee',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/4ja.webp',
    region: 'ja',
    gender: 'men',
    category: 'Jersey',
    description: "一撃必殺の美学。ミニマルなシルエットと力強い『蹴』の漢字が、サッカーの本質を表現。日の丸を背負い、技術と精神の極致を目指すプレイヤーに。",
    metaTitle: "漢字 サッカーTシャツ | Kanji Spirit - The Art of Kick | Folklore FC",
    metaDescription: "『蹴』の一文字に込められたサッカーの真髄。ミニマルなデザインと力強い筆文字。日本の精神性と技術の極致を表現した一着。",
    altText: "中央に大きく力強い『蹴』の漢字が筆文字で書かれた、日の丸をイメージした白のサッカーTシャツ。",
    keywords: ["漢字 Tシャツ", "サッカー 芸術", "Kanji Art Shirt", "ミニマル デザイン 日本"]
  },
  {
    id: 'jp-5',
    name: 'Samurai Blue Shadows - Castle Scroll',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/5ja.webp',
    region: 'ja',
    gender: 'men',
    category: 'Jersey',
    description: "歴史が動き出す。伝統的な絵巻物をイメージした背景に、城郭を駆け抜ける忍者のサッカーマッチを描写。日本の古き良き美しさと躍動感が調和。",
    metaTitle: "忍者 城郭 サッカーシャツ | Samurai Blue Shadows | Folklore FC",
    metaDescription: "絵巻物のようなサッカーマッチ。日本の城郭を舞台に忍者が躍動するアートデザイン。歴史とスポーツが融合した特別な一着。",
    altText: "日本の城を背景に、忍者がサッカーをしている様子を絵巻物スタイルで描いたグラフィックシャツ。",
    keywords: ["忍者 城 デザイン", "絵巻物 アート", "Japanese Castle Sportswear", "和風 グラフィックT"]
  },
  {
    id: 'jp-6',
    name: 'Sumo Striker - National Pride Edition',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/6ja.webp',
    region: 'ja',
    gender: 'men',
    category: 'Jersey',
    description: "国技とサッカーの最強タッグ。力士の圧倒的なパワーをサッカーに融合。富士山と鳥居を背景に、日本独自のスポーツ文化を讃えるデザイン。",
    metaTitle: "相撲 サッカーユニフォーム | Sumo Striker Japan | Folklore FC",
    metaDescription: "相撲の力強さをサッカーへ。富士山と鳥居を背負うSumo Striker。日本の国技とフットボールが交差するダイナミックなデザイン。",
    altText: "富士山と赤い鳥居を背景に、力士が豪快にサッカーボールを蹴るイラストが描かれたシャツ。",
    keywords: ["相撲 グッズ", "富士山 サッカー", "Sumo Sportswear", "日本文化 Tシャツ"]
  },
  {
    id: 'jp-7',
    name: 'Titan FC - Kaiju Domination',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/7ja.webp',
    region: 'ja',
    gender: 'men',
    category: 'Jersey',
    description: "怪獣、ピッチを支配する。スタジアムを圧倒する巨大な怪獣がサッカーボールを掴む。日本のポップカルチャーとサッカーの熱狂がぶつかり合う一枚。",
    metaTitle: "怪獣 サッカーユニフォーム | Kaiju Domination Titan FC | Folklore FC",
    metaDescription: "怪獣がスタジアムを襲う！日本のポップカルチャーを象徴する怪獣デザインのサッカーユニフォーム。圧倒的なインパクトでピッチを支配せよ。",
    altText: "スタジアムを破壊する巨大な怪獣（ゴジラ風）がサッカーボールを鷲掴みにしている迫力あるデザイン。",
    keywords: ["怪獣 デザイン", "Kaiju Fashion", "特撮 サッカー", "ポップカルチャー シャツ"]
  },
  {
    id: 'jp-8',
    name: 'Spirit of Nippon - Zen Football Circle',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/8ja.webp',
    region: 'ja',
    gender: 'men',
    category: 'Jersey',
    description: "禅の精神、円の完成。鳥居と蓮の花に囲まれ、円相（えんそう）の中でボールを操るプレイヤー。日本独自の精神性をストリートスタイルに昇華。",
    metaTitle: "禅 サッカーシャツ | Zen Football Spirit of Nippon | Folklore FC",
    metaDescription: "禅の静寂とサッカーの動。円相（Enso）の中に調和を見出すデザイン。日本独自の精神性を纏う、洗練されたストリートウェア。",
    altText: "円相（筆で描かれた円）の中にサッカープレイヤーと鳥居、蓮の花が描かれた精神的なデザインのシャツ。",
    keywords: ["禅 ファッション", "円相 デザイン", "Zen Art Soccer", "スピリチュアル スポーツウェア"]
  },
  {
    id: 'jp-9',
    name: 'Manga Focus - Intense Blue Eye',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/9ja.webp',
    region: 'ja',
    gender: 'men',
    category: 'Jersey',
    description: "究極の集中力。マンガのアートスタイルからインスピレーションを得た、青く光る瞳のデザイン。ピッチ上での一瞬の判断力を表現。",
    metaTitle: "マンガ風 サッカーTシャツ | Manga Focus Blue Eye | Folklore FC",
    metaDescription: "ブルーロックのような熱狂を。マンガ風の鋭い瞳が勝利への執念を映し出す。究極の集中力を表現したエッジの効いたデザイン。",
    altText: "マンガのコマ割りのような背景に、青く発光する鋭い瞳がアップで描かれたインパクトのあるシャツ。",
    keywords: ["マンガ デザイン", "ブルーロック風", "Anime Style Soccer", "瞳 グラフィックT"]
  },
  {
    id: 'jp-10',
    name: 'Ninja Clan - Osaka Castle Kick',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/10ja.webp',
    region: 'ja',
    gender: 'men',
    category: 'Jersey',
    description: "日本忍術、ここに極まる。伝統的な城郭を背景に、空中を舞う忍者のオーバーヘッドキックを描写。サムライブルーの精神と忍の技が融合。",
    metaTitle: "忍者 オーバーヘッド サッカーシャツ | Osaka Castle Kick | Folklore FC",
    metaDescription: "大坂城を背景に忍者が舞う！アクロバティックなオーバーヘッドキックを描いた忍者クラン・エディション。サムライブルーの誇りを胸に。",
    altText: "夜の日本の城を背景に、忍者が空中高く飛び上がりオーバーヘッドキックを決めるダイナミックなデザイン。",
    keywords: ["忍者 オーバーヘッド", "城郭 サッカー", "Ninja Skills Shirt", "ダイナミック デザイン"]
  },
  {
    id: 'jp-11',
    name: 'Samurai Blue Legends - Kitsune Spirit',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/11ja.webp',
    region: 'ja',
    gender: 'men',
    category: 'Jersey',
    description: "伝説の始まり。九尾の狐（きつね）と共にピッチに立つ若きヒーローたち。日本の誇りを胸に戦う姿を描いたアート。",
    metaTitle: "九尾の狐 サッカーユニフォーム | Kitsune Legends | Folklore FC",
    metaDescription: "九尾の狐の守護を得て。伝統的な鳥居と現代都市が交差する背景で戦うサムライブルーの伝説。神話と現代が融合したアート作品。",
    altText: "青い炎を纏った九尾の狐とサッカー選手が並び立つ、幻想的な日本都市の風景グラフィック。",
    keywords: ["九尾の狐", "Kitsune Art", "妖怪 サッカー", "Legendary Japan Jersey"]
  },
  {
    id: 'jp-12',
    name: 'Tokyo Kickoff - Mecha Manga Panel',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/12ja.webp',
    region: 'ja',
    gender: 'men',
    category: 'Jersey',
    description: "コミックの世界を纏う。巨大ロボット（メカ）と波、マンガのコマ割りをイメージした構成。日本のポップカルチャーを完璧に融合。",
    metaTitle: "メカ サッカーシャツ | Tokyo Kickoff Manga Panel | Folklore FC",
    metaDescription: "メカ、波、そしてゴール！マンガのコマ割りスタイルで日本のポップカルチャーを凝縮したTokyo Kickoff。アニメファン必見のユニフォーム。",
    altText: "巨大ロボット（メカ）が波の中から現れサッカーボールを蹴る様子をマンガのページ風にデザインしたシャツ。",
    keywords: ["メカ デザイン", "マンガ コマ割り", "Mecha Anime Shirt", "東京 ポップカルチャー"]
  },
  {
    id: 'jp-13',
    name: 'Blue Lock - Oni Mask Devotion',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/13ja.webp',
    region: 'ja',
    gender: 'men',
    category: 'Jersey',
    description: "勝利への執着、鬼の如く。迫力ある青い鬼（おに）の面がサッカーボールを掴むデザイン。限界を超える強烈なエゴを表現。",
    metaTitle: "鬼 サッカーユニフォーム | Blue Lock Oni Mask | Folklore FC",
    metaDescription: "鬼のような執念で勝利を掴め。青い鬼の面をモチーフにしたBlue Lockエディション。ピッチを支配する圧倒的なカリスマ性を表現。",
    altText: "恐ろしい形相の青い鬼の面が、鋭い爪でサッカーボールを握りしめているダークなデザイン。",
    keywords: ["鬼の面", "Blue Lock風", "Oni Mask Fashion", "エゴイスト サッカー"]
  },
  {
    id: 'jp-14',
    name: 'Dragon Soul - Sumi-e Ink Art',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/14ja.webp',
    region: 'ja',
    gender: 'men',
    category: 'Jersey',
    description: "墨絵の魂。力強い筆致で描かれた黒龍がボールを包み込む。日本の伝統的な水墨画の技法を用い、神秘的な力を表現。",
    metaTitle: "水墨画 龍 サッカーシャツ | Dragon Soul Sumi-e | Folklore FC",
    metaDescription: "筆致に宿る龍の魂。伝統的な水墨画（Sumi-e）で描かれた黒龍がピッチを舞う。神秘的な強さとしなやかさを兼ね備えた芸術的一着。",
    altText: "白地に黒い墨で描かれた力強い龍が、サッカーボールに巻き付いている水墨画スタイルのデザイン。",
    keywords: ["水墨画 龍", "Sumi-e Art", "龍 デザイン シャツ", "日本伝統 アートウェア"]
  },
  {
    id: 'jp-15',
    name: 'Azure Dragon - Sakura Majesty',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/15ja.webp',
    region: 'ja',
    gender: 'men',
    category: 'Jersey',
    description: "闘魂と美学。繊細に描かれた青龍と舞い散る桜の花。力強さの中にある日本の情緒を表現。ラグジュアリーなデザイン。",
    metaTitle: "青龍 桜 サッカーユニフォーム | Azure Dragon Sakura | Folklore FC",
    metaDescription: "青龍の威厳と桜の美学。力強さと繊細さが共存する「Azure Dragon」。洗練された和のストリートスタイルを極める一着。",
    altText: "鮮やかな青龍と、風に舞うピンクの桜の花びらが調和した豪華なグラフィックサッカーシャツ。",
    keywords: ["青龍 デザイン", "桜 サッカー", "Luxury Japan Style", "和柄 プレミアム"]
  },
  {
    id: 'jp-16',
    name: 'Ramen Striker - Gourmet Football',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/16ja.webp',
    region: 'ja',
    gender: 'men',
    category: 'Jersey',
    description: "日本の味、ピッチに登場。ラーメンの器の中にサッカー場が広がる遊び心溢れるデザイン。食文化とスポーツを融合させたアート。",
    metaTitle: "ラーメン サッカーシャツ | Ramen Striker Gourmet | Folklore FC",
    metaDescription: "ラーメンとサッカーの意外な融合！器の中に広がるフィールドと北斎の波。日本の食文化を愛するサポーターのためのユニークな一着。",
    altText: "ラーメンのどんぶりの中にサッカー場があり、具材の合間に選手がいるユニークでポップなデザイン。",
    keywords: ["ラーメン グッズ", "面白い Tシャツ", "Japanese Food Soccer", "ポップアート シャツ"]
  },
  {
    id: 'jp-17',
    name: 'Hokusai Pitch - The Great Wave Edition',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/17ja.webp',
    region: 'ja',
    gender: 'men',
    category: 'Jersey',
    description: "葛飾北斎の傑作がピッチに蘇る。伝説の『神奈川沖浪裏』を背景に、荒波と共にゴールへと舞い上がるサッカーボール。",
    metaTitle: "北斎 浪裏 サッカーシャツ | The Great Wave Hokusai | Folklore FC",
    metaDescription: "世界で最も有名な波、神奈川沖浪裏をフィールドへ。北斎の傑作とサッカーの躍動感が融合した、時代を超える芸術的スタイル。",
    altText: "葛飾北斎の「神奈川沖浪裏」を背景に、巨大な波飛沫と共に飛び出すサッカーボールを描いたデザイン。",
    keywords: ["北斎 波", "神奈川沖浪裏 Tシャツ", "Great Wave Soccer", "浮世絵 スポーツウェア"]
  },
  {
    id: 'jp-18',
    name: 'Nippon Legends - Samurai Spirit High Kick',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/18ja.webp',
    region: 'ja',
    gender: 'men',
    category: 'Jersey',
    description: "武士の魂、不屈の精神。富士山と鳥居を背負い、鎧武者が華麗なハイキックを放つ力強いデザイン。",
    metaTitle: "鎧武者 ハイキック シャツ | Samurai Spirit Nippon Legends | Folklore FC",
    metaDescription: "不屈の日本魂。富士山を背に鎧武者がハイキックを放つ。勝利への執念と侍の誇りを凝縮した、最強のストリートウェア。",
    altText: "赤い鎧を着た武士が、富士山を背景にアクロバティックなハイキックでボールを蹴るイラスト。",
    keywords: ["侍 ハイキック", "富士山 デザイン", "Samurai Spirit", "日本魂 Tシャツ"]
  },
  {
    id: 'jp-19',
    name: 'Yokai Chaos - Mythical Match Edition',
    price: 39.99,
    currency: 'USD',
    image: '/images/men/19ja.webp',
    region: 'ja',
    gender: 'men',
    category: 'Jersey',
    description: "妖怪大戦争、キックオフ。鬼、天狗、河童など、伝説の妖怪たちがピッチで繰り広げる超自然的な試合を描写。",
    metaTitle: "妖怪 サッカーユニフォーム | Yokai Chaos Mythical Match | Folklore FC",
    metaDescription: "妖怪たちの超自然的マッチ。鬼や天狗がピッチで大暴れするYokai Chaos。日本の伝承とサッカーの熱狂がぶつかり合う一枚。",
    altText: "鬼、天狗、河童などの日本の妖怪たちが混ざり合ってサッカーの試合をしている賑やかでダークなデザイン。",
    keywords: ["妖怪 デザイン", "天狗 サッカー", "Mythical Japan Jersey", "妖怪大戦争"]
  },
  
];