import { Product } from '../../types';

export const womenList: Product[] = [

  // --- فرنسا الاحترافية (FR Women - SEO & AI Optimized) ---
  {
    id: 'wfr-1',
    name: 'Victoire de Jeanne - Armure de Foot',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/1fr.webp',
    region: 'fr',
    gender: 'women',
    category: 'Jersey',
    description: "Inspiré par la force historique de Jeanne d'Arc. Ce design allie l'armure médiévale aux couleurs nationales, symbolisant une détermination inébranlable sur le terrain. Pour les guerrières qui mènent leur équipe vers la victoire.",
    // حقول SEO الاحترافية لجوجل والذكاء الاصطناعي
    metaTitle: "Maillot Foot Femme Jeanne d'Arc | Victoire de Jeanne | Folklore FC",
    metaDescription: "Découvrez le maillot exclusif Victoire de Jeanne. Fusion d'armure médiévale et de football français pour femmes. Design artistique premium. Livraison gratuite.",
    altText: "Maillot de football pour femme avec design d'armure médiévale inspiré de Jeanne d'Arc, couleurs bleu blanc rouge.",
    keywords: ["Maillot foot femme", "Jeanne d'Arc football", "France heritage jersey", "Streetwear foot Paris"]
  },
  {
    id: 'wfr-2',
    name: 'France Mode - Lignes de But',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/2fr.webp',
    region: 'fr',
    gender: 'women',
    category: 'Jersey',
    description: "L'élégance minimaliste rencontre la passion du ballon rond. Un design abstrait qui capture l'essence du mouvement et du style français contemporain. Une pièce chic pour les supporters qui privilégient le design épuré.",
    metaTitle: "Maillot de Foot Chic France Mode | Design Minimaliste | Folklore FC",
    metaDescription: "Le style français rencontre le football. Achetez notre maillot minimaliste France Mode. Idéal pour un look streetwear sophistiqué et moderne.",
    altText: "T-shirt de football blanc pour femme avec lignes bleues et rouges minimalistes et inscription France Mode.",
    keywords: ["Mode foot femme", "Minimalist football shirt", "France streetwear", "Maillot chic femme"]
  },
  {
    id: 'wfr-3',
    name: "L'Art du Jeu - Foulée Impressionniste",
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/3fr.webp',
    region: 'fr',
    gender: 'women',
    category: 'Jersey',
    description: "Célébrez le football comme un art vivant. Inspiré par les maîtres impressionnistes français, ce design capture la vitesse et l'énergie du jeu à travers des coups de pinceau vibrants.",
    metaTitle: "Maillot de Foot Artistique L'Art du Jeu | Style Impressionniste | Folklore FC",
    metaDescription: "Un maillot de foot conçu comme un chef-d'œuvre. Inspiré par l'impressionnisme français. Pour les fans de foot et d'art. Collection exclusive.",
    altText: "Design de maillot de foot avec des coups de pinceau colorés représentant une joueuse en mouvement, style peinture impressionniste.",
    keywords: ["Art football jersey", "Impressionnist shirt", "Vêtement foot artistique", "Folklore FC France"]
  },
  {
    id: 'wfr-4',
    name: 'Mona Ultras - Street Art Louvre',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/4fr.webp',
    region: 'fr',
    gender: 'women',
    category: 'Jersey',
    description: "Quand l'icône du Louvre rejoint les tribunes. La Joconde porte fièrement les couleurs de l'équipe, mélangeant culture classique et ferveur des supporters. Un hommage audacieux à l'esprit Ultras français.",
    metaTitle: "T-shirt Mona Lisa Ultras | Street Art Louvre Football | Folklore FC",
    metaDescription: "Mona Lisa devient une supportrice ! Découvrez le design Mona Ultras mêlant street art et héritage français. Un must-have pour les fans du Louvre et du foot.",
    altText: "T-shirt blanc Mona Lisa avec maquillage de supportrice et écharpe de football aux couleurs de la France.",
    keywords: ["Mona Lisa football", "Street art foot", "Ultras France shirt", "Louvre inspired jersey"]
  },
  {
    id: 'wfr-5',
    name: 'Eau de Victoire - Parfum de Championne',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/5fr.webp',
    region: 'fr',
    gender: 'women',
    category: 'Jersey',
    description: "L'essence même du succès. Ce design transforme le ballon de foot en un flacon de parfum de luxe parisien. Un symbole de sophistication pour celles qui jouent avec grâce.",
    metaTitle: "Maillot Foot Femme Eau de Victoire | Luxe Parisien | Folklore FC",
    metaDescription: "L'essence du football français dans un design de parfum de luxe. Élégance parisienne et passion sportive. Achetez la collection Eau de Victoire.",
    altText: "Design de ballon de football transformé en flacon de parfum de luxe avec étiquette dorée Eau de Victoire.",
    keywords: ["Parfum foot Paris", "Luxury football shirt", "Élégance foot femme", "Cadeau foot luxe"]
  },
  {
    id: 'wfr-6',
    name: 'Le Coq Glorieux - Allez les Bleues',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/6fr.webp',
    region: 'fr',
    gender: 'women',
    category: 'Jersey',
    description: "Le symbole national réinventé. Un coq gaulois majestueux trônant sur le ballon, orné de motifs baroques élégants. Représentez la fierté française avec une esthétique royale.",
    metaTitle: "Maillot Coq Gaulois France | Allez les Bleues | Folklore FC",
    metaDescription: "Portez fièrement le Coq Glorieux. Un design royal et baroque pour soutenir l'équipe de France féminine. Style et héritage réunis.",
    altText: "Illustration d'un coq gaulois majestueux bleu et or sur un ballon de football, texte Allez les Bleues.",
    keywords: ["Coq Gaulois foot", "Maillot France femme", "Fierté française", "Royal football jersey"]
  },
  {
    id: 'wfr-7',
    name: 'Le Tacticien - Penseur du Terrain',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/7fr.webp',
    region: 'fr',
    gender: 'women',
    category: 'Jersey',
    description: "Inspiré par le chef-d'œuvre de Rodin. Le Penseur analyse les tactiques de jeu complexes. Un design intelligent pour les passionnées qui voient le football comme un jeu d'esprit.",
    metaTitle: "Maillot Le Tacticien Rodin | Football & Philosophie | Folklore FC",
    metaDescription: "Le Penseur de Rodin revisité pour le football. Un design intellectuel et stratégique pour les passionnées du jeu tactique. Édition limitée.",
    altText: "T-shirt gris avec la statue du Penseur de Rodin assis sur un ballon de football avec des flèches tactiques en arrière-plan.",
    keywords: ["Rodin football", "Tactique foot design", "Penseur football shirt", "Art & Sport France"]
  },
  {
    id: 'wfr-8',
    name: 'Le Roi du Jeu - Éclat Solaire',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/8fr.webp',
    region: 'fr',
    gender: 'women',
    category: 'Jersey',
    description: "Inspiré par l'héritage de Versailles et du Roi Soleil. Ce blason doré célèbre la domination technique et l'élégance suprême. Régnez sur le terrain avec cette pièce de collection.",
    metaTitle: "Maillot Le Roi du Jeu | Style Versailles Soleil | Folklore FC",
    metaDescription: "Inspiré par Louis XIV et Versailles. Un maillot majestueux or et bleu pour dominer le style et le terrain. Qualité royale Folklore FC.",
    altText: "Blason doré de style baroque entourant un ballon de football avec rayons solaires, texte Le Roi du Jeu.",
    keywords: ["Versailles football", "Louis XIV jersey", "Maillot foot doré", "Heritage France"]
  },
  {
    id: 'wfr-9',
    name: 'Ma Planète - Le Petit Footballeur',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/9fr.webp',
    region: 'fr',
    gender: 'women',
    category: 'Jersey',
    description: "Inspiré par le conte intemporel de Saint-Exupéry. Ce design poétique place le sport sur un piédestal cosmique. Une touche de douceur pour les passionnées.",
    metaTitle: "Maillot Le Petit Prince Foot | Design Poétique | Folklore FC",
    metaDescription: "Achetez le maillot inspiré du Petit Prince. Un design nostalgique et poétique pour les amoureuses du football français. Édition spéciale.",
    altText: "Illustration poétique du Petit Prince debout sur un grand ballon de football dans l'espace, texte Ma Planète.",
    keywords: ["Petit Prince football", "Design foot nostalgie", "Saint-Exupéry jersey", "Maillot foot poésie"]
  },
  {
    id: 'wfr-10',
    name: 'Tous Pour Un - Mousquetaires du Terrain',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/10fr.webp',
    region: 'fr',
    gender: 'women',
    category: 'Jersey',
    description: "Célébrez l'unité avec ce design inspiré des Trois Mousquetaires. Trois rapières protégeant le ballon, symbolisant le courage et l'honneur français.",
    metaTitle: "Maillot Trois Mousquetaires Foot | Unité & Honneur | Folklore FC",
    metaDescription: "Un pour tous, tous pour le foot ! Découvrez notre design Mousquetaires. Symbole de courage et de solidarité sur le terrain.",
    altText: "Blason avec trois épées de mousquetaires croisées derrière un ballon de football classique, texte Tous Pour Un.",
    keywords: ["Mousquetaires football", "Honneur France foot", "Maillot foot solidaire", "History football jersey"]
  },
  {
    id: 'wfr-11',
    name: 'Frenchie FC - Le Supporter Branché',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/11fr.webp',
    region: 'fr',
    gender: 'women',
    category: 'Jersey',
    description: "Le charme parisien rencontre la culture foot. Ce design met en scène l'emblématique Bouledogue français avec une attitude cool. Parfait pour un style urbain typiquement français.",
    metaTitle: "T-shirt Bouledogue Français Foot | Style Urbain Paris | Folklore FC",
    metaDescription: "Affichez votre style avec Frenchie FC. Un design mignon et branché mettant en scène un bouledogue supporter. Parfait pour le streetwear parisien.",
    altText: "T-shirt noir avec un bouledogue français portant des lunettes de soleil et un maillot de foot numéro 10.",
    keywords: ["Bouledogue français foot", "Paris streetwear shirt", "Style foot branché", "Folklore FC Frenchie"]
  },

   // --- أمريكا الاحترافية (EN Women - SEO & AI Optimized) ---
  {
    id: 'wus-1',
    name: 'Liberty FC - The Torch of Play',
    price: 45.00,
    currency: 'USD',
    image: '/images/women/1us.webp',
    region: 'en',
    gender: 'women',
    category: 'Jersey',
    description: "A bold street-art tribute to American freedom and football passion. Featuring the Statue of Liberty raising a flaming soccer ball.",
    metaTitle: "Liberty FC Women's Soccer Jersey | Statue of Liberty Art | Folklore FC",
    metaDescription: "Shop the Liberty FC jersey. A unique blend of NYC street art and soccer passion. Premium quality women's streetwear inspired by American freedom.",
    altText: "Statue of Liberty holding a flaming soccer ball as a torch, urban graffiti style on a white women's t-shirt.",
    keywords: ["USA soccer jersey", "Statue of Liberty football", "Streetwear NYC", "Women's graphic soccer tee"]
  },
  {
    id: 'wus-2',
    name: "Rosie's Pitch - We Can Play It!",
    price: 45.00,
    currency: 'USD',
    image: '/images/women/2us.webp',
    region: 'en',
    gender: 'women',
    category: 'Jersey',
    description: "Inspired by the iconic symbol of female strength and empowerment. This vintage-style poster reimagines Rosie the Riveter for the soccer field.",
    metaTitle: "Rosie the Riveter Soccer Jersey | Women's Empowerment Kit | Folklore FC",
    metaDescription: "Empower your game with 'Rosie's Pitch'. A vintage tribute to strong women in sports. Iconic Rosie the Riveter soccer reimagining. Order yours now.",
    altText: "Classic Rosie the Riveter illustration flexing her muscle in a soccer kit with the text 'We Can Play It!'.",
    keywords: ["Women's empowerment sports", "Rosie the Riveter jersey", "Vintage American soccer", "Girl power football"]
  },
  {
    id: 'wus-3',
    name: 'Break The Game - Rock & Roll Strike',
    price: 45.00,
    currency: 'USD',
    image: '/images/women/3us.webp',
    region: 'en',
    gender: 'women',
    category: 'Jersey',
    description: "For the rebels on the pitch. A high-energy design blending the raw power of American rock and roll with the beautiful game.",
    metaTitle: "Rock & Roll Soccer Jersey | Rebel Style Football Shirt | Folklore FC",
    metaDescription: "Unleash your inner rebel with 'Break The Game'. Combining American rock heritage with soccer intensity. Perfect for the edgy female fan.",
    altText: "Silhouette of a rock star smashing a guitar onto a soccer ball on white t-shirt, rock and roll aesthetic.",
    keywords: ["Rock and roll soccer", "Edgy women's streetwear", "Musical football design", "Rebel jersey USA"]
  },
  {
    id: 'wus-4',
    name: 'Walk of Fame - The Golden Legend',
    price: 45.00,
    currency: 'USD',
    image: '/images/women/4us.webp',
    region: 'en',
    gender: 'women',
    category: 'Jersey',
    description: "Dedicated to the legends of the game. Inspired by the Hollywood Walk of Fame, this design features a golden soccer cleat immortalized in a star.",
    metaTitle: "Hollywood Walk of Fame Soccer Shirt | Golden Legend Jersey | Folklore FC",
    metaDescription: "Feel like a star with our Hollywood-inspired golden legend jersey. Celebrating football greatness with an iconic LA aesthetic. Limited edition.",
    altText: "Golden soccer boot inside a Hollywood star with spotlights, 'The Legend' text on a dark women's jersey.",
    keywords: ["Hollywood soccer", "LA streetwear", "Golden soccer cleat shirt", "Celebrity football style"]
  },
  {
    id: 'wus-5',
    name: 'Buffalo Charge - Unstoppable Force',
    price: 45.00,
    currency: 'USD',
    image: '/images/women/5us.webp',
    region: 'en',
    gender: 'women',
    category: 'Jersey',
    description: "Channel the raw power of the American frontier. Featuring a majestic bison charging toward the ball, representing resilience.",
    metaTitle: "Buffalo Charge Soccer Jersey | American Frontier Spirit | Folklore FC",
    metaDescription: "Unstoppable force on the field. The Buffalo Charge jersey celebrates American heritage and resilience. Tough, stylish, and unique.",
    altText: "Powerful illustration of an American bison charging at an old-style soccer ball, vintage frontier aesthetic.",
    keywords: ["American Buffalo jersey", "Bison soccer shirt", "Wild West football", "Resilient sports gear"]
  },
  {
    id: 'wus-6',
    name: 'Power Striker - Muscle Car Classic',
    price: 45.00,
    currency: 'USD',
    image: '/images/women/6us.webp',
    region: 'en',
    gender: 'women',
    category: 'Jersey',
    description: "Speed, power, and classic American soul. Inspired by legendary muscle cars bursting through the net.",
    metaTitle: "Muscle Car Soccer Jersey | Power Striker USA | Folklore FC",
    metaDescription: "Inspired by 60s muscle cars and high-speed goals. The Power Striker jersey is for the fastest players on the pitch. Classic American soul.",
    altText: "Red classic muscle car with flaming soccer ball headlights bursting through a goal net.",
    keywords: ["Muscle car soccer", "Vintage car jersey", "Speed football shirt", "American car culture"]
  },
  {
    id: 'wus-7',
    name: 'Hollywood Goals - Red Carpet Glam',
    price: 45.00,
    currency: 'USD',
    image: '/images/women/7us.webp',
    region: 'en',
    gender: 'women',
    category: 'Jersey',
    description: "Where soccer meets high-fashion glamour. Inspired by silver screen icons and a red-carpet kickoff.",
    metaTitle: "Hollywood Red Carpet Soccer Shirt | Glamour Football | Folklore FC",
    metaDescription: "Elegance meets the pitch. A glamourous tribute to Hollywood's golden age and women's soccer. Be the icon of the game.",
    altText: "Marilyn Monroe-style icon kicking a ball on a red carpet with paparazzi flashes, 'Hollywood Goals' text.",
    keywords: ["Glamour soccer jersey", "Marilyn Monroe football", "Vintage Hollywood shirt", "Red carpet sports"]
  },
  {
    id: 'wus-8',
    name: 'Goal Diner - Serving Daily',
    price: 45.00,
    currency: 'USD',
    image: '/images/women/8us.webp',
    region: 'en',
    gender: 'women',
    category: 'Jersey',
    description: "A retro 1950s diner aesthetic. Our roller-skating waitress is serving goals daily with vintage American charm.",
    metaTitle: "Retro 50s Diner Soccer Shirt | Goal Diner Jersey | Folklore FC",
    metaDescription: "Serving goals daily! A nostalgic 1950s American diner design for the fun-loving soccer fan. Retro vibes, modern quality.",
    altText: "Waitress on roller skates kicking a ball amidst flying burgers and shakes, neon 'Goal Diner' sign.",
    keywords: ["1950s diner sports", "Retro American jersey", "Nostalgic soccer shirt", "Fun women's football tee"]
  },
  {
    id: 'wus-9',
    name: 'Liberty FC NYC - Minimalist Line Art',
    price: 45.00,
    currency: 'USD',
    image: '/images/women/9us.webp',
    region: 'en',
    gender: 'women',
    category: 'Jersey',
    description: "Sophistication meets NYC. This elegant line-art design features Lady Liberty balancing the game with grace.",
    metaTitle: "Minimalist Lady Liberty Soccer Shirt | NYC Line Art | Folklore FC",
    metaDescription: "Clean, modern, and iconic. Our NYC line art jersey features a minimalist Lady Liberty. Perfect for high-end urban streetwear.",
    altText: "Minimalist brown line art of Lady Liberty holding a soccer ball on a white women's shirt.",
    keywords: ["Minimalist soccer jersey", "NYC line art football", "Lady Liberty streetwear", "Modern US soccer"]
  },
  {
    id: 'wus-10',
    name: 'Street Sound FC - Boombox Lioness',
    price: 45.00,
    currency: 'USD',
    image: '/images/women/10us.webp',
    region: 'en',
    gender: 'women',
    category: 'Jersey',
    description: "Turn up the volume. Combining hip-hop heritage with football culture, featuring a crowned lioness ruling the urban beats.",
    metaTitle: "Hip Hop Soccer Jersey | Street Sound FC Lioness | Folklore FC",
    metaDescription: "Represent the rhythm of the city. A powerful lioness on a boombox, merging hip-hop vibes with football. Urban American pride.",
    altText: "Crowned lioness sitting on a vintage boombox with soccer ball speakers, graffiti background.",
    keywords: ["Hip hop football shirt", "Urban lioness jersey", "Boombox soccer tee", "Streetwear music kit"]
  },
  {
    id: 'wus-11',
    name: 'Varsity Soccer USA - Eagle Power',
    price: 45.00,
    currency: 'USD',
    image: '/images/women/11us.webp',
    region: 'en',
    gender: 'women',
    category: 'Jersey',
    description: "The classic American campus look. Featuring a powerful bald eagle in a varsity-style crest.",
    metaTitle: "USA Varsity Soccer Eagle Jersey | American College Style | Folklore FC",
    metaDescription: "Get the iconic American campus look. High-impact varsity eagle design celebrating US soccer excellence and athletic pride.",
    altText: "Powerful bald eagle wearing a jersey holding a soccer ball, varsity style typography USA.",
    keywords: ["Varsity soccer USA", "American Eagle jersey", "College style football", "Athletic campus wear"]
  },
  {
    id: 'wus-12',
    name: 'Wanted: Dead or Alive - The Game Thief',
    price: 45.00,
    currency: 'USD',
    image: '/images/women/12us.webp',
    region: 'en',
    gender: 'women',
    category: 'Jersey',
    description: "The Wild West's most wanted striker. A vintage 'Wanted' poster design for the players who are dangerously talented.",
    metaTitle: "Wild West Wanted Soccer Shirt | Cowboy Game Thief | Folklore FC",
    metaDescription: "The most wanted striker in the West. Unique vintage outlaw poster design for the dangerously good players. Legendary style.",
    altText: "Vintage brown 'Wanted Dead or Alive' poster featuring a female cowboy holding a golden soccer ball.",
    keywords: ["Wild West football", "Cowboy soccer jersey", "Outlaw sports shirt", "Vintage American poster tee"]
  },
  {
    id: 'wus-13',
    name: 'Outlaw Striker - Smoke & Revolvers',
    price: 45.00,
    currency: 'USD',
    image: '/images/women/13us.webp',
    region: 'en',
    gender: 'women',
    category: 'Jersey',
    description: "Unleash the rebel spirit. A gritty design featuring a cowboy skull and crossed revolvers with smoking soccer balls.",
    metaTitle: "Outlaw Striker Skull Jersey | Rebel Western Soccer | Folklore FC",
    metaDescription: "Fearless and gritty. The Outlaw Striker design represents the tough spirit of the American frontier. Bold streetwear for winners.",
    altText: "Cowboy skull with hat and crossed revolvers firing smoking soccer balls on a dark jersey.",
    keywords: ["Skull soccer jersey", "Western rebel football", "Gothic American streetwear", "Smoking gun sports"]
  },

  // --- اليابان الاحترافية (JA Women - SEO & AI Optimized) ---
  {
    id: 'wja-1',
    name: '氷の抱擁 - Frost Queen',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/1ja.webp',
    region: 'ja',
    gender: 'women',
    category: 'Jersey',
    description: "雪女の伝説をフィールドへ。冷徹なまでのコントロールと、一瞬で試合を凍りつかせるゴールセンス。氷のように鋭い攻撃を仕掛けるプレイヤーに捧げる一着。",
    metaTitle: "雪女 サッカーユニフォーム | Frost Queen Jersey | Folklore FC",
    metaDescription: "雪女の伝説にインスパイアされた「氷の抱擁」ユニフォーム。冷徹なストライカーのためのアートデザイン。高品質なストリートウェアを今すぐチェック。",
    altText: "雪女がサッカーボールを凍らせる幻想的なイラストが描かれた黒のレディースTシャツ。",
    keywords: ["サッカー女子ユニフォーム", "雪女 デザイン", "Japanese Heritage Jersey", "和柄 ストリートウェア"]
  },
  {
    id: 'wja-2',
    name: '深海の宝 - Ocean Guardian',
    price: 45.00,
    currency: 'EUR',
    image: '/images/WOMEN/2ja.webp',
    region: 'ja',
    gender: 'women',
    category: 'Jersey',
    description: "深海の神秘とサッカーの情熱が融合。龍神に見守られながら、ピッチの底から勝利を掴み取る。エレガントで力強い、水のようなプレースタイルのために。",
    metaTitle: "龍神 サッカーシャツ | Ocean Guardian Women's Kit | Folklore FC",
    metaDescription: "深海の龍神をモチーフにした「深海の宝」ユニフォーム。エレガントで力強いプレースタイルを演出する日本限定デザイン。送料無料。",
    altText: "深海で龍と共にサッカーボールを掲げる女性を描いた鮮やかな青のグラフィックTシャツ。",
    keywords: ["龍神 サッカー", "深海デザイン ユニフォーム", "Japanese Dragon Sportswear", "女子サッカー ウェア"]
  },
  {
    id: 'wja-3',
    name: '霊的支配 - Kitsune Spirit',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/3ja.webp',
    region: 'ja',
    gender: 'women',
    category: 'Jersey',
    description: "九尾の狐がもたらす、変幻自在のゲームメイク。相手を惑わし、華麗なテクニックでピッチを支配する。伝統的な美しさとモダンなストリートスタイルが交差するデザイン。",
    metaTitle: "九尾の狐 サッカーユニフォーム | Kitsune Spirit Jersey | Folklore FC",
    metaDescription: "九尾の狐の魔力を纏う。変幻自在なテクニックを象徴する「霊的支配」デザイン。伝統とモダンが融合したプレミアムな一着。",
    altText: "九尾の狐を背負った巫女風の女性と光るサッカーボールのイラスト。",
    keywords: ["九尾の狐 グッズ", "妖怪 サッカーユニフォーム", "Kitsune Streetwear Japan", "和風 スポーツウェア"]
  },
  {
    id: 'wja-4',
    name: 'ネオン・ストライカー - Cyber Pitch',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/4ja.webp',
    region: 'ja',
    gender: 'women',
    category: 'Jersey',
    description: "東京の夜を駆け抜ける、未来のストライカー。サイバーパンクな美学とサッカーのスピード感を凝縮。最先端のファッションを追求するサポーターに向けた一着。",
    metaTitle: "サイバーパンク サッカーシャツ | Cyber Pitch Tokyo | Folklore FC",
    metaDescription: "近未来の東京をイメージしたネオン・ストライカー。サイバーパンク美学とスポーツの融合。エッジの効いたストリートスタイルを求めるあなたへ。",
    altText: "ネオンが輝く東京の街をスケートボードで駆け抜けるサイバーパンクな女性とサッカーボール。",
    keywords: ["サイバーパンク ファッション", "東京 ストリートウェア", "Cyberpunk Soccer Jersey", "ネオン デザイン シャツ"]
  },
  {
    id: 'wja-5',
    name: '紙の奇跡 - Origami Grace',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/5ja.webp',
    region: 'ja',
    gender: 'women',
    category: 'Jersey',
    description: "一折一折に込められた勝利への願い。折り鶴がピッチを舞い、奇跡のゴールを導く。日本の伝統工芸と女子サッカーのしなやかさが共鳴するデザイン。",
    metaTitle: "折り鶴 サッカーユニフォーム | Origami Grace Jersey | Folklore FC",
    metaDescription: "日本の伝統「折り紙」をテーマにした「紙の奇跡」。しなやかさと勝利への願いを込めたアートデザイン。プレミアムな品質をお届けします。",
    altText: "巨大な折り鶴と渦巻く模様の中に横たわる女性を描いた芸術的なサッカーTシャツ。",
    keywords: ["折り紙 デザイン", "和柄 ユニフォーム", "Origami Art Sportswear", "日本伝統 スポーツウェア"]
  },
  {
    id: 'wja-6',
    name: '炎の舞 - Festival Flare',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/6ja.webp',
    region: 'ja',
    gender: 'women',
    category: 'Jersey',
    description: "祭りの熱狂がスタジアムに火をつける。情熱的なダンスのように、ピッチを華やかに彩る。日本の魂を揺さぶる、伝統の炎を纏った情熱的なサポーターに。",
    metaTitle: "祭り サッカーシャツ | Japanese Festival Flare | Folklore FC",
    metaDescription: "日本の祭りの熱狂をフィールドへ。情熱的な「炎の舞」デザインで、スタジアムの視線を独占。和の魂を纏うプレミアムシャツ。",
    altText: "祭りの提灯を背景に、炎のサッカーボールを蹴る着物姿の女性のイラスト。",
    keywords: ["日本 祭り グッズ", "情熱 サッカーウェア", "Festival Style Jersey", "炎 デザイン Tシャツ"]
  },
  {
    id: 'wja-7',
    name: '雷神の一撃 - Storm Goddess',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/7ja.webp',
    region: 'ja',
    gender: 'women',
    category: 'Jersey',
    description: "雷神がフィールドに降臨。轟く雷鳴とともに、一瞬の閃光で試合を決める。圧倒的なパワーとスピードを象徴する、大胆な稲妻が走るデザイン。",
    metaTitle: "雷神 サッカーユニフォーム | Raijin Storm Goddess | Folklore FC",
    metaDescription: "圧倒的なスピードを象徴する「雷神の一撃」。稲妻のように鋭い攻撃を仕掛けるプレイヤーのための神話的デザイン。今すぐ購入。",
    altText: "太鼓を背負った雷神風の戦士が稲妻を纏ったサッカーボールを蹴る迫力あるイラスト。",
    keywords: ["雷神 サッカー", "稲妻 デザイン シャツ", "Japanese Mythology Jersey", "パワー系 スポーツウェア"]
  },
  {
    id: 'wja-8',
    name: '魂の筆 - Calligraphy Strike',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/8ja.webp',
    region: 'ja',
    gender: 'women',
    category: 'Jersey',
    description: "一筆書きの美学。ピッチというキャンバスに、魂の込もったシュートを描く。書道のアート性とスポーツの躍動感が融合した、日本独自のストリートウェア。",
    metaTitle: "書道 サッカーシャツ | Japanese Calligraphy Strike | Folklore FC",
    metaDescription: "書道の力強い筆致をサッカーに。一筆書きの美学を追求した「魂の筆」ユニフォーム。アートとスポーツが完璧に融合した一着。",
    altText: "巨大な筆でサッカーボールを描く女性のモノクロ書道風イラスト。",
    keywords: ["書道 デザイン Tシャツ", "墨絵 サッカーユニフォーム", "Zen Art Sportswear", "日本文化 ストリートウェア"]
  },
  {
    id: 'wja-9',
    name: '雅な技 - Kimono Grace',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/9ja.webp',
    region: 'ja',
    gender: 'women',
    category: 'Jersey',
    description: "浮世絵の美学をピッチへ。着物を纏った優雅な動きから放たれる、一撃必殺のシュート。日本の伝統美とスポーツの躍動感が完璧に融合したアートピース。",
    metaTitle: "浮世絵 サッカーユニフォーム | Ukiyo-e Kimono Grace | Folklore FC",
    metaDescription: "浮世絵の優雅さをフィールドへ。着物姿のプレースタイルを象徴する「雅な技」。日本独自の美意識を纏うプレミアムな一着。",
    altText: "浮世絵風のタッチで描かれた、華やかな着物を着てサッカーボールを蹴る女性。",
    keywords: ["浮世絵 デザイン", "着物 サッカーユニフォーム", "Ukiyo-e Art Shirt", "雅 スポーツウェア"]
  },
  {
    id: 'wja-10',
    name: '不良少女 - Urban Rebel',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/10ja.webp',
    region: 'ja',
    gender: 'women',
    category: 'Jersey',
    description: "ストリートのルールは自分で決める。日本の「スケバン」文化とサッカーの反骨精神をミックスした、エッジの効いたデザイン。周囲に流されない強い意志を持つあなたに。",
    metaTitle: "スケバン サッカーシャツ | Urban Rebel Delinquent Girl | Folklore FC",
    metaDescription: "日本の「不良少女」文化をオマージュ。反骨精神溢れるアーバン・リベル・デザイン。自分だけのスタイルを貫くサポーターへ。",
    altText: "グラフィティの壁を背景に、サッカーボールを持ったスケバン風の女子学生イラスト。",
    keywords: ["スケバン ファッション", "不良文化 グッズ", "Japanese School Rebel", "ストリート系 サッカーシャツ"]
  },
  {
    id: 'wja-11',
    name: '桜嵐 - Sakura Storm',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/11ja.webp',
    region: 'ja',
    gender: 'women',
    category: 'Jersey',
    description: "舞い散る桜吹雪は、勝利の旋風。ピッチを華麗に舞い、嵐のようなスピードでゴールを奪う。神話的な美しさとダイナミックな力が共存する特別なデザイン。",
    metaTitle: "桜 サッカーユニフォーム | Sakura Storm Pink Jersey | Folklore FC",
    metaDescription: "勝利の旋風を巻き起こす「桜嵐」。舞い散る桜の花びらとダイナミックな動きを表現した日本限定デザイン。春のピッチを彩る一着。",
    altText: "ピンクの桜吹雪の渦の中に舞う女性戦士とサッカーボールの幻想的なグラフィック。",
    keywords: ["桜 デザイン シャツ", "ピンク サッカーユニフォーム", "Sakura Sportswear", "和柄 レディース"]
  },
  {
    id: 'wja-12',
    name: '戦士の魂 - Samurai Valor',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/12ja.webp',
    region: 'ja',
    gender: 'women',
    category: 'Jersey',
    description: "甲冑を纏った現代の女武芸者。扇子を操るような繊細なタッチと、侍のような揺るぎない覚悟でピッチに立つ。誇り高き精神を持つプレイヤーのための鎧。",
    metaTitle: "侍 サッカーユニフォーム | Samurai Valor Women's Armor | Folklore FC",
    metaDescription: "侍の魂を現代のピッチへ。甲冑をモチーフにした「戦士の魂」デザイン。誇り高き精神を持つ女性プレイヤーのためのプレミアムな鎧。",
    altText: "赤い甲冑を纏い、扇子を持ってサッカーボールを操る侍風の女性イラスト。",
    keywords: ["侍 ユニフォーム", "Samurai Soccer Gear", "甲冑 デザイン シャツ", "武士道 スポーツウェア"]
  },
  {
    id: 'wja-13',
    name: 'なでしこジャパン - Kimono Striker',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/13ja.webp',
    region: 'ja',
    gender: 'women',
    category: 'Jersey',
    description: "月明かりに照らされた伝統的な風景の中で、歴史を塗り替える一蹴。日本の精神「大和なでしこ」の強さとしなやかさを表現したデザイン。",
    metaTitle: "なでしこ サッカーシャツ | Moonlit Kimono Striker | Folklore FC",
    metaDescription: "大和なでしこの精神を体現。月明かりの下で戦う「なでしこジャパン」インスパイア・デザイン。強さとしなやかさを兼ね備えた一着。",
    altText: "満月の夜、伝統的な日本の風景の中でサッカーボールを蹴る着物姿の女性。",
    keywords: ["なでしこ サッカー", "大和なでしこ シャツ", "Nadeshiko Japan Spirit", "和風 グラフィックT"]
  },
  {
    id: 'wja-14',
    name: '侍の栄光 - Blade of Glory',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/14ja.webp',
    region: 'ja',
    gender: 'women',
    category: 'Jersey',
    description: "一振りで勝負を決める、名刀のような鋭さ。ディフェンスを切り裂く、緻密で力強い攻撃を象徴するカタナ・アート。ピッチに栄光を刻むためのユニフォーム。",
    metaTitle: "刀 サッカーユニフォーム | Blade of Glory Katana Art | Folklore FC",
    metaDescription: "名刀のような鋭いシュートを。カタナと桜をモチーフにした「侍の栄光」デザイン。ディフェンスを切り裂くストライカーのための必携アイテム。",
    altText: "黒い円の中に紫の日本刀がサッカーボールを切り裂くようなクールなイラスト。",
    keywords: ["日本刀 サッカー", "刀 デザイン グッズ", "Katana Soccer Jersey", "栄光 スポーツウェア"]
  },

  // --- السعودية الاحترافية (AR Women - SEO & AI Optimized) ---

  {
    id: 'wsa-1',
    name: 'تيشيرت شموخ - فخر النخلة',
    price: 85.00,
    currency: 'SAR',
    image: '/images/women/1sa.webp',
    region: 'ar',
    gender: 'women',
    category: 'Jersey',
    description: "تصميم يجسد الأنفة والعلو المستوحى من نخلة العطاء السعودية. يمزج بين الرمز الوطني العريق وكرة القدم بلمسة معدنية عصرية.",
    metaTitle: "تيشيرت شموخ النسائي | فخر التراث السعودي | Folklore FC",
    metaDescription: "تسوقي تيشيرت شموخ المستوحى من النخلة السعودية. تصميم يجمع بين التراث والقوة الرياضية. جودة ممتازة وتوصيل سريع في المملكة.",
    altText: "تيشيرت رياضي نسائي أسود عليه شعار نخلة معدني مدمج مع كرة قدم بأسلوب فني سعودي.",
    keywords: ["تيشيرت نسائي سعودي", "ملابس رياضية تراثية", "نخلة السعودية", "ازياء ستريت وير الرياض"]
  },
  {
    id: 'wsa-2',
    name: 'تيشيرت هيبة - سيوف النصر',
    price: 85.00,
    currency: 'SAR',
    image: '/images/women/2sa.webp',
    region: 'ar',
    gender: 'women',
    category: 'Jersey',
    description: "رمز القوة والأصالة. يتميز بتصميم السيوف العربية المتقاطعة مع كرة القدم بأسلوب 'الغرافيتي' الحديث.",
    metaTitle: "تيشيرت هيبة سيوف النصر | ملابس رياضية سعودية | Folklore FC",
    metaDescription: "أضيفي الهيبة لإطلالتك مع تيشيرت سيوف النصر. تصميم غرافيتي يجمع بين السيف العربي وشغف الكرة. اطلبي الآن من فولكلور إف سي.",
    altText: "تيشيرت أبيض نسائي عليه رسم غرافيتي لسيوف عربية متقاطعة مع كرة قدم باللون الأخضر.",
    keywords: ["تيشيرت غرافيتي سعودي", "سيوف النصر", "ملابس اليوم الوطني", "ستريت وير سعودي"]
  },
  {
    id: 'wsa-3',
    name: 'تيشيرت شغف - قلب السدو',
    price: 85.00,
    currency: 'SAR',
    image: '/images/women/3sa.webp',
    region: 'ar',
    gender: 'women',
    category: 'Jersey',
    description: "حب اللعبة محفور في التراث. تصميم على شكل قلب منقوش بزخارف السدو الأصيلة، يحيط بكرة القدم.",
    metaTitle: "تيشيرت قلب السدو النسائي | شغف كرة القدم | Folklore FC",
    metaDescription: "عبري عن حبك للكرة بتصميم قلب السدو التراثي. تيشيرت يجمع بين أصالة الحياكة السعودية وروح الرياضة العالمية. تسوقي الآن.",
    altText: "تيشيرت أسود نسائي عليه شعار قلب كبير بنقوش السدو الأحمر والأسود بوسطه كرة قدم.",
    keywords: ["نقوش سدو", "تيشيرت تراثي نسائي", "هدايا رياضية سعودية", "فولكلور إف سي"]
  },
  {
    id: 'wsa-4',
    name: 'تيشيرت عزم - إرادة الملاعب',
    price: 85.00,
    currency: 'SAR',
    image: '/images/women/4sa.webp',
    region: 'ar',
    gender: 'women',
    category: 'Jersey',
    description: "للمرأة التي لا تعرف المستحيل. يبرز التصميم خيالاً للاعبة كرة قدم بلمسات هندسية خضراء، تعبيراً عن العزم السعودي.",
    metaTitle: "تيشيرت عزم للمرأة الرياضية | تمكين وإرادة | Folklore FC",
    metaDescription: "تيشيرت عزم يحتفي بإرادة المرأة السعودية في الملاعب. تصميم عصري يعكس القوة والتمكين. مثالي للنادي والإطلالات اليومية.",
    altText: "تيشيرت أبيض عليه رسم ظلي للاعبة كرة قدم سعودية بلمسات فنية باللون الأخضر وكلمة عزم.",
    keywords: ["تمكين المرأة السعودية", "ملابس رياضية نسائية", "لاعبة كرة قدم", "تيشيرت عزم"]
  },
  {
    id: 'wsa-5',
    name: 'تيشيرت رأس الحربة - فن الهجوم',
    price: 85.00,
    currency: 'SAR',
    image: '/images/women/5sa.webp',
    region: 'ar',
    gender: 'women',
    category: 'Jersey',
    description: "تصميم ديناميكي مستوحى من مهارة الـ 'فنتازيا' الكروية. يدمج بين حركة اللاعبة والخط العربي المتطاير.",
    metaTitle: "تيشيرت رأس الحربة | فن الخط العربي والكرة | Folklore FC",
    metaDescription: "تصميم رأس الحربة يدمج بين سرعة الهجوم وجمال الخط العربي. قطعة فنية رياضية فريدة لكل لاعبة ومشرقة. جودة عالية.",
    altText: "تيشيرت أسود مع لاعبة كرة قدم محجبة في وضعية قفز محاطة بحروف عربية طائرة.",
    keywords: ["الخط العربي", "تيشيرت رأس الحربة", "ملابس رياضية للمحجبات", "فن رياضي"]
  },
  {
    id: 'wsa-6',
    name: 'تيشيرت رؤية - نظرة المستقبل',
    price: 85.00,
    currency: 'SAR',
    image: '/images/women/6sa.webp',
    region: 'ar',
    gender: 'women',
    category: 'Jersey',
    description: "نظرة ثاقبة نحو هدف واحد. تصميم فني يركز على عيون البطلة التي ترى المستقبل خلف شباك المرمى.",
    metaTitle: "تيشيرت رؤية المستقبل | عيون البطلة السعودية | Folklore FC",
    metaDescription: "تيشيرت رؤية يجسد طموح المرأة السعودية. تصميم فني رائع يركز على نظرة الإصرار. خامة قطنية مريحة وأناقة لا مثيل لها.",
    altText: "تيشيرت أبيض يظهر رسم عيون امرأة ببرقع فني من خيوط المرمى باللون الأخضر.",
    keywords: ["رؤية 2030", "تيشيرت طموح", "ازياء سعودية حديثة", "ملابس بنات رياضية"]
  },
  {
    id: 'wsa-7',
    name: 'تيشيرت مجد - العصر الذهبي',
    price: 85.00,
    currency: 'SAR',
    image: '/images/women/7sa.webp',
    region: 'ar',
    gender: 'women',
    category: 'Jersey',
    description: "تصميم أيقوني باللون الذهبي يحتفي بتاريخ البطولات. خيال البطلة وسط زخارف تراثية، يرمز إلى المجد.",
    metaTitle: "تيشيرت مجد الذهبي | فخر الإنجازات السعودية | Folklore FC",
    metaDescription: "احتفلي بالمجد مع تيشيرت العصر الذهبي. تصميم ملكي يجمع بين الذهب والتراث. قطعة حصرية لمحبات التميز والبطولات.",
    altText: "تيشيرت أسود عليه رسم ذهبي لامع لامرأة رياضية وكلمة مجد بخط عربي عريض.",
    keywords: ["تيشيرت ذهبي", "إنجازات السعودية", "تيشيرت مجد", "ملابس شتوية رياضية"]
  },
  {
    id: 'wsa-8',
    name: 'تيشيرت انطلاقة - فجر جديد',
    price: 85.00,
    currency: 'SAR',
    image: '/images/women/8sa.webp',
    region: 'ar',
    gender: 'women',
    category: 'Jersey',
    description: "يجسد السرعة والانسيابية في اللعب. خطوط زرقاء وسوداء تحيط باللاعبة أثناء تسديد الكرة.",
    metaTitle: "تيشيرت انطلاقة الرياضي | سرعة وحيوية | Folklore FC",
    metaDescription: "انطلقي نحو هدفك مع تيشيرت انطلاقة. تصميم يفيض بالطاقة والحركة. مثالي لممارسة الرياضة والأنشطة الخارجية.",
    altText: "تيشيرت أبيض عليه حركة لاعبة كرة قدم بخطوط زرقاء انسيابية سريعة.",
    keywords: ["تيشيرت رياضي سريع", "انطلاقة", "ملابس جيم نسائية", "سوق السعودية"]
  },
  {
    id: 'wsa-9',
    name: 'تيشيرت ثبات - نقوش النصر',
    price: 85.00,
    currency: 'SAR',
    image: '/images/women/9sa.webp',
    region: 'ar',
    gender: 'women',
    category: 'Jersey',
    description: "حيث يلتقي الفن بالتكتيك. تصميم يدمج بين جمال نقوش الحناء التراثية ومخططات اللعب الذكية.",
    metaTitle: "تيشيرت ثبات بنقش الحناء | تكتيك وأصالة | Folklore FC",
    metaDescription: "تيشيرت ثبات يجمع بين جمال الحناء وذكاء تكتيك كرة القدم. تصميم فريد يعكس شخصية المرأة السعودية القوية والذكية.",
    altText: "تيشيرت أسود يظهر قبضة يد مزينة بنقوش حناء دقيقة بداخلها مخططات تكتيكية لكرة القدم.",
    keywords: ["نقش حناء", "تيشيرت ثبات", "تكتيك كرة قدم", "تراث سعودي مطور"]
  },
  {
    id: 'wsa-10',
    name: 'تيشيرت سد منيع - درع الدفاع',
    price: 85.00,
    currency: 'SAR',
    image: '/images/women/10sa.webp',
    region: 'ar',
    gender: 'women',
    category: 'Jersey',
    description: "للمدافعات اللواتي لا يعرفن الانكسار. يبرز التصميم لاعبة بزي تكتيكي عصري تصد الكرة بدرع من الطاقة.",
    metaTitle: "تيشيرت سد منيع | درع الدفاع النسائي | Folklore FC",
    metaDescription: "كوني السد المنيع في فريقك. تيشيرت بتصميم تكتيكي قوي يعبر عن الدفاع والصلابة. اطلبي تيشيرت الدرع الآن.",
    altText: "تيشيرت أبيض يصور لاعبة دفاع سعودية تصد كرة قدم متفجرة بدرع طاقة زجاجي.",
    keywords: ["دفاع كرة قدم", "سد منيع", "ملابس رياضية قوية", "درع الطاقة"]
  },
  {
    id: 'wsa-11',
    name: 'تيشيرت صقر - شموخ الجارح',
    price: 85.00,
    currency: 'SAR',
    image: '/images/women/11sa.webp',
    region: 'ar',
    gender: 'women',
    category: 'Jersey',
    description: "مستوحى من الصقر العربي الأصيل، رمز الحدة والسرعة. تصميم يجمع بين قوة الصقر والخط العربي الذهبي.",
    metaTitle: "تيشيرت الصقر العربي | حدة وسرعة | Folklore FC",
    metaDescription: "تيشيرت الصقر يمثل الحدة والشموخ في الملاعب السعودية. تصميم ذهبي فخم يعكس روح الجارح. اطلبي قطعة من الفخامة.",
    altText: "تيشيرت أسود عليه رسم صقر جارح ينقض على كرة قدم مع كلمة صقر بخط ذهبي.",
    keywords: ["الصقر العربي", "تيشيرت صقر", "فخامة سعودية", "ملابس رياضية ذهبية"]
  },
  {
    id: 'wsa-12',
    name: 'تيشيرت قبضة من حديد - الكرة الذهبية',
    price: 85.00,
    currency: 'SAR',
    image: '/images/women/12sa.webp',
    region: 'ar',
    gender: 'women',
    category: 'Jersey',
    description: "تجسيد لروح الإصرار والتحكم. يظهر التصميم حارسة مرمى تسيطر على كرة ذهبية سائلة.",
    metaTitle: "تيشيرت قبضة من حديد | حارسة المرمى | Folklore FC",
    metaDescription: "سيطري على المباراة مع تيشيرت قبضة من حديد. تصميم مذهل لحارسة المرمى والكرة الذهبية. قوة وإصرار في كل تفصيل.",
    altText: "تيشيرت أبيض يظهر يدي حارسة مرمى تمسكان بكرة ذهبية سائلة وكلمة قبضة من حديد.",
    keywords: ["حارسة مرمى", "قبضة من حديد", "تيشيرت حارسة", "الكرة الذهبية"]
  },
  {
    id: 'wsa-13',
    name: 'تيشيرت فخر المملكة - KSA Pride',
    price: 85.00,
    currency: 'SAR',
    image: '/images/women/13sa.webp',
    region: 'ar',
    gender: 'women',
    category: 'Jersey',
    description: "الاعتزاز بالهوية في أبهى صوره. دمج فني لشعار المملكة (السيفين والنخلة) مع كرة القدم.",
    metaTitle: "تيشيرت فخر المملكة KSA | شعار السيفين والنخلة | Folklore FC",
    metaDescription: "ارتدي فخر المملكة. تيشيرت يجمع بين شعار السعودية وكرة القدم بألوان ملكية. الخيار الأمثل للمشجعات السعوديات.",
    altText: "تيشيرت أسود يظهر شعار السيفين والنخلة يتوسطه كرة قدم باللون الأخضر والذهبي.",
    keywords: ["KSA Pride", "فخر المملكة", "تيشيرت السيفين والنخلة", "شعار السعودية"]
  },
  {
    id: 'wsa-14',
    name: 'تيشيرت نبض اللعبة - شغف التفاصيل',
    price: 85.00,
    currency: 'SAR',
    image: '/images/women/14sa.webp',
    region: 'ar',
    gender: 'women',
    category: 'Jersey',
    description: "تصميم شاعري يربط القلب بكرة القدم عبر خطوط الحناء المعقدة. يعبر عن الشغف الحقيقي الذي يجري في العروق.",
    metaTitle: "تيشيرت نبض اللعبة | قلب وشغف الحناء | Folklore FC",
    metaDescription: "تيشيرت نبض اللعبة يربط قلبك بكرة القدم. تصميم شاعري بنقوش الحناء يعبر عن عشق الكرة في السعودية. جودة قطنية رائعة.",
    altText: "تيشيرت أبيض عليه رسم لقلب بشري منقوش بالحناء يمسك كرة قدم.",
    keywords: ["نبض اللعبة", "تيشيرت قلب", "شغف كرة القدم", "حناء سعودي"]
  },
  {
    id: 'wsa-15',
    name: 'تيشيرت تركيز قاتل - عين البطلة',
    price: 85.00,
    currency: 'SAR',
    image: '/images/women/15sa.webp',
    region: 'ar',
    gender: 'women',
    category: 'Jersey',
    description: "النظرة التي تحسم المباريات. تصميم فني يركز على عيون اللاعبة من خلف البرقع العصري.",
    metaTitle: "تيشيرت تركيز قاتل | عيون القناصة السعودية | Folklore FC",
    metaDescription: "النظرة التي لا تخطئ الهدف. تيشيرت تركيز قاتل يجسد دقة القناصة في الملعب. تصميم عصري يعبر عن الهوية والقوة.",
    altText: "تيشيرت أبيض يظهر عيون امرأة خلف برقع عصري يحيط به إعصار من ذرات الكرة.",
    keywords: ["تركيز قاتل", "عيون البطلة", "تيشيرت قناصة", "ازياء سعودية نسائية"]
  },


  // --- إسبانيا الاحترافية (ES Women - SEO & AI Optimized) ---
  {
    id: 'wes-1',
    name: 'Pura Pasión - Danza del Gol',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/1es.webp',
    region: 'es',
    gender: 'women',
    category: 'Jersey',
    description: "La elegancia del flamenco se traslada al terreno de juego. Un diseño que captura la fuerza y el espíritu de España.",
    metaTitle: "Camiseta de Fútbol Flamenco | Pura Pasión España | Folklore FC",
    metaDescription: "Siente el arte del flamenco en el campo. Camiseta exclusiva Pura Pasión para mujer. Diseño artístico inspirado en la cultura española. Calidad premium.",
    altText: "Camiseta blanca con ilustración de una bailaora de flamenco con vestido rojo y amarillo transformándose en llamas alrededor de un balón.",
    keywords: ["Camiseta fútbol mujer", "Diseño flamenco", "Moda urbana España", "Jersey fútbol artístico"]
  },
  {
    id: 'wes-2',
    name: 'Ritmo en el Área - Tacón y Balón',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/2es.webp',
    region: 'es',
    gender: 'women',
    category: 'Jersey',
    description: "Siente el compás del juego. Inspirado en el calzado tradicional del baile español, simbolizando la precisión y la gracia.",
    metaTitle: "Camiseta Ritmo y Fútbol | Diseño Tacón Español | Folklore FC",
    metaDescription: "Donde el baile se une al gol. Descubre la camiseta 'Ritmo en el Área'. Estética única que celebra el calzado tradicional y la destreza futbolística.",
    altText: "Ilustración de un zapato de flamenco rojo con lunares negros golpeando un balón de fútbol sobre fondo blanco.",
    keywords: ["Tacón y Balón", "Cultura española fútbol", "Ropa deportiva mujer", "Diseño creativo España"]
  },
  {
    id: 'wes-3',
    name: 'Caos Rítmico - Rebelde Flamenca',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/3es.webp',
    region: 'es',
    gender: 'women',
    category: 'Jersey',
    description: "Para las que rompen las reglas con estilo. Una fusión de estética punk y tradición española.",
    metaTitle: "Camiseta Rebelde Flamenca | Estilo Punk Español | Folklore FC",
    metaDescription: "Fusión audaz de tradición y rebeldía. La camiseta Caos Rítmico redefine el estilo urbano español. Para jugadoras con carácter indomable.",
    altText: "Diseño estilo grafiti de una bailarina de flamenco con botas militares y alambre de espino alrededor de un balón.",
    keywords: ["Punk flamenco", "Streetwear rebelde", "Camiseta fútbol alternativa", "Moda España mujer"]
  },
  {
    id: 'wes-4',
    name: 'La Nobleza - Galope de Campeona',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/4es.webp',
    region: 'es',
    gender: 'women',
    category: 'Jersey',
    description: "Inspirado en la elegancia ecuestre andaluza. Representa la distinción y la firmeza en el terreno de juego.",
    metaTitle: "Camiseta Ecuestre Andaluza | La Nobleza Fútbol | Folklore FC",
    metaDescription: "Elegancia y poderío. Camiseta inspirada en la tradición ecuestre de Andalucía. Diseño exclusivo para las reinas del campo de juego.",
    altText: "Mujer vestida de amazona montando un caballo blanco que pisa un balón de fútbol, estilo ilustración clásica.",
    keywords: ["Andalucía ecuestre", "Nobleza española", "Camiseta fútbol elegante", "Hípica y fútbol"]
  },
  {
    id: 'wes-5',
    name: 'Azulejo Floral - Romper el Ritmo',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/5es.webp',
    region: 'es',
    gender: 'women',
    category: 'Jersey',
    description: "La belleza de la cerámica tradicional se mezcla con la frescura de las rosas y el dinamismo del deporte.",
    metaTitle: "Camiseta Diseño Azulejo | Cerámica Española Fútbol | Folklore FC",
    metaDescription: "Arte tradicional en tu piel. Camiseta inspirada en los azulejos clásicos y rosas españolas. Sofisticación urbana y pasión deportiva.",
    altText: "Balón de fútbol rodeado de rosas púrpuras sobre un fondo de mosaico de azulejos azules tradicionales rotos.",
    keywords: ["Azulejos españoles", "Diseño floral fútbol", "Cerámica arte urbano", "Moda femenina España"]
  },
  {
    id: 'wes-6',
    name: 'Pasión Eterna - Sagrado Corazón',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/6es.webp',
    region: 'es',
    gender: 'women',
    category: 'Jersey',
    description: "El fútbol como religión. Un diseño místico que eleva el balón a un símbolo de devoción eterna.",
    metaTitle: "Camiseta Pasión Eterna | Sagrado Corazón Fútbol | Folklore FC",
    metaDescription: "Amor incondicional por los colores. Diseño místico de devoción futbolística con estética de arte sacro español. Edición especial limitada.",
    altText: "Balón de fútbol en llamas con una corona de espinas y una espada clavada, rodeado de rosas rojas y encaje.",
    keywords: ["Arte sacro fútbol", "Sagrado corazón", "Devoción deportiva", "Camiseta fútbol gótica"]
  },
  {
    id: 'wes-7',
    name: 'Soplo de Victoria - El Abanico',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/7es.webp',
    region: 'es',
    gender: 'women',
    category: 'Jersey',
    description: "Frescura y elegancia. Inspirado en el abanico español, simboliza el aire de cambio y la brisa de triunfo.",
    metaTitle: "Camiseta Abanico Español | Soplo de Victoria | Folklore FC",
    metaDescription: "Elegancia en movimiento. Camiseta inspirada en el icónico abanico español. Un soplo de aire fresco para tu estilo futbolístico.",
    altText: "Abanico español de encaje rojo desplegado detrás de un balón de fútbol en movimiento con pétalos negros volando.",
    keywords: ["Abanico español", "Moda fútbol mujer", "Accesorios tradicionales", "Folklore FC España"]
  },
  {
    id: 'wes-8',
    name: 'La Conquista - Velas al Viento',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/8es.webp',
    region: 'es',
    gender: 'women',
    category: 'Jersey',
    description: "Navega hacia la gloria. Inspirado en los grandes galeones históricos, transformando balones en velas.",
    metaTitle: "Camiseta Galeón Histórico | La Conquista Fútbol | Folklore FC",
    metaDescription: "Inspirada en la era de los descubrimientos. Camiseta 'La Conquista' con diseño de galeón español. Lidera tu equipo hacia nuevos horizontes.",
    altText: "Galeón español navegando con velas en forma de balones de fútbol antiguos sobre olas doradas.",
    keywords: ["Historia de España", "Galeón español", "Náutica fútbol", "Camiseta épica mujer"]
  },
  {
    id: 'wes-9',
    name: 'Ritmo Victorioso - Compás de Gol',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/9es.webp',
    region: 'es',
    gender: 'women',
    category: 'Jersey',
    description: "Siente el choque de las castañuelas en cada jugada. Celebra la percusión tradicional unida al estallido del gol.",
    metaTitle: "Camiseta Castañuelas Fútbol | Ritmo Victorioso | Folklore FC",
    metaDescription: "El sonido de la victoria. Camiseta exclusiva inspirada en las castañuelas y el compás del gol. Música y deporte en un diseño único.",
    altText: "Dos castañuelas de madera chocando violentamente contra un balón de fútbol con chispas musicales.",
    keywords: ["Castañuelas", "Percusión española", "Ritmo fútbol", "Streetwear música"]
  },
  {
    id: 'wes-10',
    name: 'El Toro - Fuerza Indomable',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/10es.webp',
    region: 'es',
    gender: 'women',
    category: 'Jersey',
    description: "El símbolo supremo de la valentía española. Representa la resistencia y la bravura necesarias en el campo.",
    metaTitle: "Camiseta Toro de España | Fuerza Indomable Fútbol | Folklore FC",
    metaDescription: "Bravura y resistencia. La icónica figura del toro unida a la pasión por el fútbol. Una camiseta potente para jugadoras decididas.",
    altText: "Balón de fútbol con cuernos de toro rompiendo una red con manchas de pintura roja y negra.",
    keywords: ["Toro de España", "Bravura fútbol", "Fuerza deportiva", "Icono español"]
  },
  {
    id: 'wes-11',
    name: 'La Reina - Maestría en el Ruedo',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/11es.webp',
    region: 'es',
    gender: 'women',
    category: 'Jersey',
    description: "Inspirado en la figura de la matadora, celebra el control y la elegancia bajo presión.",
    metaTitle: "Camiseta Matadora Fútbol | La Reina del Ruedo | Folklore FC",
    metaDescription: "Controla el juego con maestría. Camiseta inspirada en el traje de luces y la valentía del ruedo. Elegancia suprema para la mujer.",
    altText: "Mujer vestida con traje de torero tradicional haciendo una faena con un capote rojo y un balón de fútbol.",
    keywords: ["Traje de luces", "Matadora fútbol", "Elegancia española", "Reina del campo"]
  },
  {
    id: 'wes-12',
    name: 'Rebelde por Siempre - Escudo Urbano',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/12es.webp',
    region: 'es',
    gender: 'women',
    category: 'Jersey',
    description: "Donde la tradición se encuentra con la calle. Un escudo adornado con rosas y graffiti.",
    metaTitle: "Camiseta Rebelde por Siempre | Escudo Urbano España | Folklore FC",
    metaDescription: "Orgullo y rebeldía. Un diseño de escudo heráldico renovado con estética callejera y rosas. Defiende tu identidad con estilo.",
    altText: "Escudo metálico con un balón central, decorado con grafitis coloridos y rosas púrpuras vibrantes.",
    keywords: ["Heráldica urbana", "Grafiti España", "Escudo fútbol", "Ropa rebelde mujer"]
  },
  {
    id: 'wes-13',
    name: 'La Victoria - Baile en el Área',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/13es.webp',
    region: 'es',
    gender: 'women',
    category: 'Jersey',
    description: "La silueta de una bailaora flamenca se funde con el balón en un movimiento eterno de gracia y pasión.",
    metaTitle: "Camiseta Bailaora Fútbol | La Victoria Flamenca | Folklore FC",
    metaDescription: "Gracia y pasión desbordante. Camiseta con silueta artística de bailaora de flamenco dominando el balón. Estética sofisticada y deportiva.",
    altText: "Silueta negra de una bailaora de flamenco con falda roja voluminosa sobre un balón de fútbol.",
    keywords: ["Bailaora flamenco", "Movimiento fútbol", "Arte español", "Diseño silueta"]
  },
  {
    id: 'wes-14',
    name: 'Toque Mágico - Melodía de Gol',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/14es.webp',
    region: 'es',
    gender: 'women',
    category: 'Jersey',
    description: "El fútbol es armonía. Las cuerdas de una guitarra clásica envuelven el balón, simbolizando la técnica exquisita.",
    metaTitle: "Camiseta Guitarra Española | Toque Mágico Fútbol | Folklore FC",
    metaDescription: "Armonía y técnica. Camiseta inspirada en la guitarra española y el toque legendario del fútbol nacional. Música y deporte en sintonía.",
    altText: "Cuerdas de guitarra envolviendo un balón de fútbol dorado con notas musicales y salpicaduras de pintura azul.",
    keywords: ["Guitarra española", "Técnica fútbol", "Armonía deportiva", "Música y goles"]
  },
  {
    id: 'wes-15',
    name: 'Nueva Era - Mantón de Malla',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/15es.webp',
    region: 'es',
    gender: 'women',
    category: 'Jersey',
    description: "Homenaje al icónico mantón de Manila, rediseñado para la cultura urbana con bordados tradicionales.",
    metaTitle: "Camiseta Mantón de Manila | Nueva Era Streetwear | Folklore FC",
    metaDescription: "Tradición rediseñada. Camiseta inspirada en el mantón de Manila con estética ciberpunk y flores bordadas. El futuro de la moda deportiva.",
    altText: "Balón de fútbol envuelto en un mantón de seda púrpura con bordados de flores brillantes y flecos dinámicos.",
    keywords: ["Mantón de Manila", "Bordados españoles", "Cyberpunk España", "Moda urbana lujo"]
  },
  {
    id: 'wes-16',
    name: 'La Furia - Corazón del Ruedo',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/16es.webp',
    region: 'es',
    gender: 'women',
    category: 'Jersey',
    description: "El espíritu de la selección encarnado en un toro en plena carga con determinación inquebrantable.",
    metaTitle: "Camiseta La Furia Roja | Corazón del Ruedo | Folklore FC",
    metaDescription: "Siente la furia española. Diseño potente de toro cargando con bufanda de la selección. Determinación y garra para ganar.",
    altText: "Toro bravo cargando hacia un balón con una bufanda roja de España al cuello, estilo artístico dinámico.",
    keywords: ["La Furia Roja", "Selección española", "Toro bravo", "Garra futbolística"]
  },
  {
    id: 'wes-17',
    name: 'Don Quijote del Área - Hasta el Final',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/17es.webp',
    region: 'es',
    gender: 'women',
    category: 'Jersey',
    description: "Inspirado en Cervantes. Una caballera moderna enfrentando gigantes por sus sueños de gloria.",
    metaTitle: "Camiseta Don Quijote Fútbol | Honor y Sueños | Folklore FC",
    metaDescription: "Lucha por lo imposible. Camiseta inspirada en Don Quijote de la Mancha. Para jugadoras que defienden el honor hasta el final.",
    altText: "Dibujo a tinta de una caballera andante sobre un caballo frente a un balón de fútbol gigante, estilo clásico Cervantes.",
    keywords: ["Don Quijote", "Literatura española", "Honor fútbol", "Diseño épico"]
  },
  {
    id: 'wes-18',
    name: 'Herradura de Gloria - Fuerza Pura',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/18es.webp',
    region: 'es',
    gender: 'women',
    category: 'Jersey',
    description: "La suerte de la herradura y la pasión del clavel español se unen para conquistar la victoria.",
    metaTitle: "Camiseta Herradura y Claveles | Suerte y Fuerza | Folklore FC",
    metaDescription: "Atrae la gloria. Camiseta que combina el símbolo de la herradura con la belleza del clavel español. Fuerza pura para el éxito.",
    altText: "Herradura dorada antigua expulsando claveles rojos vibrantes alrededor de un balón de fútbol.",
    keywords: ["Claveles españoles", "Suerte deportiva", "Símbolos España", "Ropa deportiva mujer"]
  },
  {
    id: 'wes-19',
    name: 'Danza Explosiva - Puro Caos',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/19es.webp',
    region: 'es',
    gender: 'women',
    category: 'Jersey',
    description: "Un torbellino de color y arte urbano que redefine el espíritu del flamenco y la calle.",
    metaTitle: "Camiseta Danza Explosiva | Arte Urbano Flamenco | Folklore FC",
    metaDescription: "Energía sin límites. Diseño abstracto y colorido que fusiona el baile flamenco con el arte callejero contemporáneo. Única y vibrante.",
    altText: "Bailaora en estilo pop-art rodeada de patrones hexagonales amarillos y salpicaduras de pintura rosa.",
    keywords: ["Pop art flamenco", "Caos creativo", "Streetwear colorido", "Moda fútbol vanguardia"]
  },
  {
    id: 'wes-20',
    name: 'Legado Modernista - España Artista',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/20es.webp',
    region: 'es',
    gender: 'women',
    category: 'Jersey',
    description: "Homenaje al genio de Gaudí y el arte del mosaico trencadís. Colores vibrantes y formas orgánicas.",
    metaTitle: "Camiseta Inspiración Gaudí | Legado Modernista Fútbol | Folklore FC",
    metaDescription: "Viste una obra de arte. Camiseta inspirada en Gaudí y los mosaicos de Barcelona. Creatividad y elegancia modernista española.",
    altText: "Balón de fútbol diseñado con estilo de mosaico trencadís colorido y salamandras modernistas alrededor.",
    keywords: ["Gaudí fútbol", "Trencadís Barcelona", "Modernismo español", "Arte para vestir"]
  },
  {
    id: 'wes-21',
    name: 'Vitral de Pasión - Fe Eterna',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/21es.webp',
    region: 'es',
    gender: 'women',
    category: 'Jersey',
    description: "Inspirado en los majestuosos rosetones de las catedrales. El fútbol como una devoción sagrada.",
    metaTitle: "Camiseta Vitral Catedral | Fe Eterna Fútbol | Folklore FC",
    metaDescription: "Belleza divina en el juego. Diseño inspirado en los vitrales de las catedrales españolas. Fe inquebrantable en tu equipo.",
    altText: "Rosetón de catedral gótica con cristales de colores rompiéndose alrededor de un balón de fútbol central.",
    keywords: ["Vitrales España", "Arquitectura gótica", "Fe futbolística", "Diseño artístico lujo"]
  },
  {
    id: 'wes-22',
    name: 'Lidia Futuro - Fuego Urbano',
    price: 45.00,
    currency: 'EUR',
    image: '/images/women/22es.webp',
    region: 'es',
    gender: 'women',
    category: 'Jersey',
    description: "Estética cyberpunk fusionada con la valentía del ruedo. Un matador robótico domando la competición.",
    metaTitle: "Camiseta Cyberpunk Matador | Lidia Futuro España | Folklore FC",
    metaDescription: "El futuro de la lidia. Estética matador robótico y fuego para las delanteras más letales. Diseño futurista de alto impacto.",
    altText: "Torero robótico con capa tecnológica frente a una calavera de toro en llamas y un balón futurista.",
    keywords: ["Cyberpunk matador", "Futurismo español", "Ropa deportiva agresiva", "Estética avanzada"]
  },


  // ... ضع هنا باقي منتجات النساء فقط
];